"""Static presentation content: terminology, limitations, disclaimers.

Two things live here rather than in the pages.

**The vocabulary.**  The project keeps several quantities separate that a
dashboard is under constant pressure to merge: signal quality, calibrated
classification confidence, ensemble disagreement, predictive entropy,
probability margin, and regression interval width.  Each is a different
question about a different object, and a shared label would be the first
step to a shared axis.  :data:`TERMINOLOGY` states each one's display
name and what it is not, and the pages read from it rather than typing a
caption by hand.

**The limitations.**  These are typed records, not Markdown scraped at
run time.  A page that parses prose renders nothing when the prose is
reworded, and the limitations page is the one that must never quietly go
blank.  The records carry a document reference so the reader can open the
full statement.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from engagevr.schemas.dashboard import LimitationRecord

#: What each page must state about its own evidence.
SYNTHETIC_PAGE_NOTE = (
    "Every number on this page was computed from SYNTHETIC data generated "
    "by this repository from a data-generating process it also wrote. It "
    "measures whether the software is wired together correctly. It is not "
    "model accuracy, not engagement validity, not cognitive-load validity, "
    "and not evidence about any person."
)

#: Shown wherever a run family reports metrics for several estimators.
DESCRIPTIVE_SORTING_NOTE = (
    "Descriptive sorting only. No model, fusion strategy, threshold, or "
    "policy in this repository is a champion, a winner, or a recommended "
    "choice. Ordering a column does not select anything."
)

#: Shown on the signal-quality page, next to every chart.
SIGNAL_QUALITY_NOTE = (
    "Signal quality describes measurement reliability and availability. It "
    "is not engagement, not cognitive load, and not model confidence. A "
    "window with poor signal quality is a window that was hard to measure, "
    "not a person who was disengaged."
)

#: Shown on the personalization page.
PERSONALIZATION_NOTE = (
    "Population and personalized results are reported separately over "
    "identical evaluation windows. A difference between them on synthetic "
    "data is a synthetic metric difference, not a benefit, not an "
    "improvement, and not evidence that personalization helps anyone. "
    "Negative differences are displayed exactly as recorded."
)

#: Shown on the adaptation page.
ADAPTATION_NOTE = (
    "This page reports CONTROLLER BEHAVIOUR: how often a deterministic "
    "software policy proposed a change and which guard stopped it when it "
    "did not. How often a controller acts is not how well it works. No "
    "adaptation in this repository has been dispatched to an environment, "
    "acknowledged by one, or evaluated with a participant."
)

#: Shown beside the Milestone 8 guard-free comparison.
CONTROLLER_COMPARISON_NOTE = (
    "SOFTWARE-CONTROLLER ACTION-FREQUENCY COMPARISON. This shows only that "
    "the temporal guards mechanically reduce how often the controller acts. "
    "It is not a claim that either controller is better, safer, or more "
    "effective for any person."
)

#: Shown on the uncertainty page.
SELECTIVE_PREDICTION_NOTE = (
    "Coverage and accepted-set performance are reported together and never "
    "separately. An abstention is a deliberate decision to withhold an "
    "actionable estimate; it is not an error and is not counted as one. An "
    "unavailable window is different again: nothing was withheld, because "
    "nothing was produced."
)

#: Shown wherever a static experimental condition is displayed.
STATIC_MODE_NOTE = (
    "A static run is a legitimate experimental control condition. Every "
    "policy decision holding is the expected behaviour of that condition, "
    "not a malfunction, not a disabled participant, and not low engagement."
)

#: Shown wherever pseudonymous identifiers appear.
SUBJECT_ID_NOTE = (
    "Subject and session identifiers in this repository are pseudonymous "
    "labels generated by software. They are shown for research audit only. "
    "Per-subject views are group-level software diagnostics; this "
    "dashboard does not rank subjects, resolve identifiers to people, or "
    "display any personal information."
)


#: Display label for each recorded ``data_source`` value, in words.
#:
#: The recorded strings are the project's own
#: :class:`~engagevr.schemas.session.DataSource` members plus the
#: catalogue's ``"mixed"``.  They are terse, and ``public_dataset`` in a
#: monospaced cell is easy to skim past, so every provenance surface
#: renders this label beside the raw value rather than instead of it.
#: The raw value is what the artifact recorded; the label is what a
#: reader must not miss.
DATA_SOURCE_LABELS: dict[str, str] = {
    "synthetic": "SYNTHETIC",
    "public_dataset": "PUBLIC",
    "live": "LIVE",
    "mixed": "MIXED",
}

#: What each data source does and does not establish.
#:
#: Each entry ends on the same point, because it is the one a reader is
#: most likely to supply for themselves in the wrong direction: where the
#: bytes came from is not a statement that a study was designed,
#: labelled, approved, or validated.  Neither *public* nor *live* is a
#: shortcut to scientific eligibility.
DATA_SOURCE_NOTES: dict[str, str] = {
    "synthetic": (
        "SYNTHETIC data source: generated by this repository from a "
        "data-generating process it also wrote. It is a software "
        "self-check and is never scientific evidence about any person."
    ),
    "public_dataset": (
        "PUBLIC data source: content originating in a public research "
        "dataset. Being public does not make anything here scientifically "
        "eligible. Eligibility is declared by the artifact, this "
        "repository has validated nothing, and a public corpus says where "
        "the bytes came from, not that a study was designed, labelled, "
        "approved, or validated for this target."
    ),
    "live": (
        "LIVE data source: content recorded from a session running on this "
        "machine. Being live does not make it scientifically eligible; "
        "'live' says where the bytes came from, not that a study was "
        "designed, labelled, approved, or validated."
    ),
    "mixed": (
        "MIXED data sources: this artifact records more than one origin. "
        "The strictest reading present applies, and no part of it becomes "
        "scientifically eligible by being mixed with another."
    ),
}

#: Said where a data source was recorded that this vocabulary has no
#: wording for. The value is shown, never guessed at or normalised away.
UNKNOWN_DATA_SOURCE_NOTE = (
    "This data source is not one this dashboard has wording for. It is "
    "displayed exactly as recorded and is not interpreted. Nothing about "
    "an unrecognised source makes it scientifically eligible."
)

#: Said where nothing recorded a data source at all.
ABSENT_DATA_SOURCE_LABEL = "Unavailable — no data source is recorded"


def data_source_label(value: str | None) -> str:
    """The display label for one recorded data-source string.

    Returns the label and the recorded value together.  Showing only the
    label would hide what the artifact actually says; showing only the
    recorded value leaves ``public_dataset`` to be noticed rather than
    read.
    """
    if value is None or not value.strip():
        return ABSENT_DATA_SOURCE_LABEL
    recorded = value.strip()
    label = DATA_SOURCE_LABELS.get(recorded)
    if label is None:
        return f"UNRECOGNISED (recorded as {recorded!r})"
    return f"{label} (recorded as {recorded!r})"


def data_source_statement(value: str | None) -> str:
    """What one recorded data source does and does not establish."""
    if value is None or not value.strip():
        return (
            "No data source is recorded for this evidence. Its absence is "
            "stated rather than filled in, and nothing here is "
            "scientifically eligible."
        )
    return DATA_SOURCE_NOTES.get(value.strip(), UNKNOWN_DATA_SOURCE_NOTE)


def data_source_statements(values: Sequence[str]) -> tuple[str, ...]:
    """The statements for every recorded data source, deduplicated in order."""
    seen: list[str] = []
    for value in values:
        statement = data_source_statement(value)
        if statement not in seen:
            seen.append(statement)
    return tuple(seen)


@dataclass(frozen=True)
class Term:
    """One project quantity, its display name, and what it is not."""

    key: str
    display_name: str
    definition: str
    is_not: tuple[str, ...]


#: The quantities this dashboard must keep apart, and their exact names.
TERMINOLOGY: tuple[Term, ...] = (
    Term(
        key="signal_quality",
        display_name="Signal quality",
        definition=(
            "How reliably a modality could be measured in a window, and "
            "whether it was available at all."
        ),
        is_not=(
            "not engagement",
            "not cognitive load",
            "not model confidence",
            "not a probability that a prediction is correct",
        ),
    ),
    Term(
        key="calibrated_confidence",
        display_name="Calibrated classification confidence",
        definition=(
            "The maximum calibrated class probability for a window. It "
            "states how often outcomes of this kind occurred at this "
            "predicted probability in the evaluated folds."
        ),
        is_not=(
            "not certainty",
            "not signal quality",
            "not defined for a regression target",
        ),
    ),
    Term(
        key="predictive_entropy",
        display_name="Predictive entropy",
        definition=(
            "The Shannon entropy of the predicted class-probability vector, in nats."
        ),
        is_not=(
            "not a confidence score",
            "not a probability",
            "not comparable across different numbers of classes",
        ),
    ),
    Term(
        key="probability_margin",
        display_name="Probability margin",
        definition=(
            "The largest predicted class probability minus the second largest."
        ),
        is_not=("not the confidence score", "not an interval width"),
    ),
    Term(
        key="ensemble_disagreement",
        display_name="Ensemble disagreement",
        definition=(
            "How much the per-modality experts differ from one another about a window."
        ),
        is_not=(
            "not calibrated uncertainty",
            "not a confidence score",
            "not signal quality",
            "not a probability of being wrong",
        ),
    ),
    Term(
        key="fusion_support_weight",
        display_name="Fusion support weight",
        definition=(
            "The normalized weight a modality's expert contributed to a "
            "fused prediction."
        ),
        is_not=(
            "not a probability of correctness",
            "not model confidence",
            "not a measure of that modality's importance to the construct",
        ),
    ),
    Term(
        key="interval_width",
        display_name="Regression prediction-interval width",
        definition=(
            "The width of a split-conformal prediction interval, in the "
            "regression target's own units."
        ),
        is_not=(
            "not a probability",
            "not confined to [0, 1]",
            "not convertible into a confidence score",
            "never displayed as 1 - width",
        ),
    ),
    Term(
        key="selective_coverage",
        display_name="Selective coverage",
        definition=(
            "Accepted windows divided by every evaluated window, including "
            "those for which no prediction was available."
        ),
        is_not=("not accuracy", "not an interval coverage probability"),
    ),
    Term(
        key="abstention_rate",
        display_name="Abstention rate",
        definition=(
            "Windows for which an actionable estimate was deliberately "
            "withheld, divided by every evaluated window."
        ),
        is_not=("not an error rate", "not the unavailable count"),
    ),
    Term(
        key="empirical_interval_coverage",
        display_name="Empirical interval coverage",
        definition=(
            "The fraction of accepted regression windows whose recorded "
            "interval contained the observed value."
        ),
        is_not=(
            "not selective coverage",
            "not a guarantee",
            "not established across subjects",
        ),
    ),
)

#: Keyed lookup for page captions.
TERMINOLOGY_BY_KEY: dict[str, Term] = {term.key: term for term in TERMINOLOGY}


def term_caption(key: str) -> str:
    """One-line caption naming a quantity and what it is not.

    Pages call this instead of writing a caption by hand, so the same
    quantity is described the same way on every page it appears on.
    """
    term = TERMINOLOGY_BY_KEY[key]
    negations = ", ".join(term.is_not)
    return f"{term.display_name}. {term.definition} It is {negations}."


#: The standing limitations of this repository as of Milestone 9.
LIMITATIONS: tuple[LimitationRecord, ...] = (
    LimitationRecord(
        identifier="no-validated-engagement-labels",
        title="No validated participant-labelled engagement dataset exists",
        detail=(
            "Every engagement target in this repository is synthetic or "
            "absent. No questionnaire score, expert annotation, or "
            "validated participant label has ever been collected here, so "
            "no number anywhere in this dashboard is evidence about "
            "engagement."
        ),
        reference="docs/LIMITATIONS.md",
    ),
    LimitationRecord(
        identifier="no-validated-cognitive-load-labels",
        title="No validated participant-labelled cognitive-load dataset exists",
        detail=(
            "The same holds for cognitive load. The construct is latent, "
            "no validated label has been collected, and the synthetic "
            "targets were written by this repository."
        ),
        reference="docs/LIMITATIONS.md",
    ),
    LimitationRecord(
        identifier="no-human-subject-adaptation-evaluation",
        title="No human-subject evaluation of adaptation has been performed",
        detail=(
            "The Milestone 8 policy has never been evaluated with a "
            "participant. Nobody has judged whether its proposals are "
            "appropriate, acceptable, or useful, and no adaptation has "
            "been dispatched to a running environment."
        ),
        reference="docs/ADAPTIVE_ENVIRONMENT.md",
    ),
    LimitationRecord(
        identifier="physical-webcam-validation-pending",
        title="Physical-webcam validation is pending",
        detail=(
            "The capture, face, head-pose, and rPPG pipelines have not been "
            "validated against a physical camera on this machine. No "
            "V4L2 device is present."
        ),
        reference="docs/LIMITATIONS.md",
    ),
    LimitationRecord(
        identifier="ubfc-rppg-evaluation-pending",
        title="Public-dataset rPPG evaluation is pending",
        detail=(
            "The UBFC-rPPG adapter validates a dataset layout only. The "
            "full decode-to-heart-rate path has never been executed "
            "against the dataset, and no rPPG accuracy figure exists."
        ),
        reference="docs/DATASETS.md",
    ),
    LimitationRecord(
        identifier="unity-validation-pending",
        title="Unity compilation and runtime validation are pending",
        detail=(
            "The Unity desktop task is checked in as source only. It has "
            "never been compiled or run, so the protocol has been "
            "exercised from the Python side alone."
        ),
        reference="docs/UNITY_SETUP.md",
    ),
    LimitationRecord(
        identifier="synthetic-confidence-evidence",
        title="All current confidence and coverage evidence is synthetic",
        detail=(
            "Calibration quality, selective coverage, abstention rates, and "
            "risk-coverage curves in this repository were computed on "
            "synthetic data. They describe the generator this repository "
            "wrote, not real-world calibration or reliability."
        ),
        reference="docs/UNCERTAINTY_AND_ABSTENTION.md",
    ),
    LimitationRecord(
        identifier="conformal-exchangeability-unestablished",
        title="Conformal exchangeability is not established for grouped data",
        detail=(
            "The split-conformal interval guarantee assumes exchangeable "
            "calibration and test points. Windows from different "
            "participants are not exchangeable, so the marginal coverage "
            "guarantee must not be claimed across subjects."
        ),
        reference="docs/UNCERTAINTY_AND_ABSTENTION.md",
    ),
    LimitationRecord(
        identifier="adaptation-defaults-are-engineering-choices",
        title="Adaptation thresholds and mappings are engineering defaults",
        detail=(
            "The 3x3 state-to-direction mapping, the dwell requirement, the "
            "cooldown, the bounds, and the session budget were chosen by "
            "the author to be conservative. None was derived from evidence "
            "and none is psychologically validated, pedagogically optimal, "
            "therapeutic, or known to be safe."
        ),
        reference="docs/ADAPTIVE_ENVIRONMENT.md",
    ),
    LimitationRecord(
        identifier="dashboard-is-not-evidence",
        title="This dashboard displays evidence; it does not create any",
        detail=(
            "Every view here reads an artifact a previous milestone wrote. "
            "Selecting, filtering, aggregating, or plotting a synthetic "
            "value does not make it scientific evidence, and this "
            "dashboard has no control that could."
        ),
        reference="docs/DASHBOARD.md",
    ),
)


def unresolved_limitations() -> tuple[LimitationRecord, ...]:
    """Limitations that still stand."""
    return tuple(record for record in LIMITATIONS if not record.resolved)


__all__ = [
    "ABSENT_DATA_SOURCE_LABEL",
    "ADAPTATION_NOTE",
    "CONTROLLER_COMPARISON_NOTE",
    "DATA_SOURCE_LABELS",
    "DATA_SOURCE_NOTES",
    "DESCRIPTIVE_SORTING_NOTE",
    "LIMITATIONS",
    "PERSONALIZATION_NOTE",
    "SELECTIVE_PREDICTION_NOTE",
    "SIGNAL_QUALITY_NOTE",
    "STATIC_MODE_NOTE",
    "SUBJECT_ID_NOTE",
    "SYNTHETIC_PAGE_NOTE",
    "TERMINOLOGY",
    "TERMINOLOGY_BY_KEY",
    "UNKNOWN_DATA_SOURCE_NOTE",
    "Term",
    "data_source_label",
    "data_source_statement",
    "data_source_statements",
    "term_caption",
    "unresolved_limitations",
]
