"""Milestone 7 CLI: uncertainty-aware inference and selective prediction.

``uncertainty-demo`` / ``uncertainty-train`` derive a confidence
representation (classification) or a conformal prediction interval
(regression), apply an explicit selective-prediction rule, and report
coverage together with accepted-set performance.

Kept in its own module so ``__main__`` stays a thin dispatcher and so the
Milestone 7 commands can be tested without importing the webcam, rPPG, or
WebSocket code paths.

The ``*-demo`` command operates on SYNTHETIC data and prints a permanent
disclaimer.  ``*-train --mode scientific`` refuses any dataset whose
predictors or targets are synthetic or whose target provenance is unstated.

No command in this module prints "safe confidence", "trusted prediction",
"optimal threshold", "best uncertainty method", "validated abstention", or
"production threshold".  A synthetic coverage curve is not evidence of
real-world calibration, reliability, safety, or usefulness, and the printed
output says so.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

from engagevr.schemas.experiments import SOFTWARE_SELF_CHECK_BANNER, EvaluationMode
from engagevr.schemas.targets import TargetName, UnsupportedTargetError
from engagevr.schemas.uncertainty import PredictionSource

#: Printed by every command in this module.
_PERMANENT_DISCLAIMER = (
    "EngageVR produces ESTIMATES from software measurements. Nothing here is "
    "a medical, diagnostic, psychological, or clinical conclusion, and no "
    "number printed by these commands is experimental evidence about any "
    "person."
)

_SYNTHETIC_BANNER = (
    "=== SYNTHETIC DATA ===\n"
    "Every row and every target below was generated by software from a known\n"
    "latent process. No person was recorded. No metric computed from this\n"
    "data is model accuracy, engagement validity, cognitive-load validity, or\n"
    "evidence of any kind, and none may be compared with a published result\n"
    "on real data."
)

_UNCERTAINTY_NOTE = (
    "Confidence, signal quality, probability calibration, and ensemble "
    "disagreement are four different things and are reported in four "
    "different fields. A synthetic confidence or coverage curve is not "
    "evidence of real-world calibration, reliability, safety, or usefulness. "
    "No threshold below is optimal, validated, or a production threshold."
)

_GATE_NOTE = (
    "The adaptation gate reports only whether an ALREADY-CHOSEN action may be "
    "acted upon. It does not choose an adaptation, does not set difficulty or "
    "scene content, and sends no message anywhere. Adaptation policy is "
    "Milestone 8."
)

_SOURCE_CHOICES = sorted(
    {s.value for s in PredictionSource}
    | {s.value.replace("_", "-") for s in PredictionSource}
)


def add_parsers(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the Milestone 7 subcommands on an existing subparser set."""
    demo = sub.add_parser(
        "uncertainty-demo",
        help=(
            "Report confidence or conformal intervals, abstention, and "
            "coverage on a SYNTHETIC dataset."
        ),
    )
    _add_uncertainty_arguments(demo)
    demo.add_argument(
        "--output", type=str, default="artifacts/experiments/m7-uncertainty-demo"
    )

    train = sub.add_parser(
        "uncertainty-train",
        help=(
            "Fit an uncertainty-aware selective-prediction evaluation on a "
            "windowed-feature dataset."
        ),
    )
    _add_uncertainty_arguments(train)
    train.add_argument(
        "--mode",
        type=str,
        default="self-check",
        choices=["self-check", "scientific"],
        help="Scientific mode rejects synthetic predictors or targets.",
    )
    train.add_argument(
        "--output", type=str, default="artifacts/experiments/uncertainty-run"
    )


def _add_uncertainty_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dataset", type=str, default="artifacts/datasets/m5-synthetic.parquet"
    )
    parser.add_argument(
        "--target",
        type=str,
        default=TargetName.ENGAGEMENT_CLASS.value,
        choices=[t.value for t in TargetName],
    )
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--source",
        type=str,
        default=None,
        choices=_SOURCE_CHOICES,
        help=(
            "Prediction source. Only sources whose probabilities pass through "
            "the Milestone 5 calibration step are offered; a LATE-fusion fused "
            "vector is not calibrated and is deliberately absent."
        ),
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help=(
            "Population confidence threshold in [0, 1]. An engineering "
            "default, not an optimum."
        ),
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=None,
        help="Nominal conformal miscoverage, strictly between 0 and 1.",
    )
    parser.add_argument(
        "--maximum-interval-width",
        type=float,
        default=None,
        help=(
            "Abstain when a prediction interval is wider than this. A width "
            "in the target's own units, not a probability."
        ),
    )
    parser.add_argument(
        "--interval-width-grid",
        type=str,
        default=None,
        help=(
            "Comma-separated maximum interval widths to sweep, in the "
            "target's own units, e.g. '0,0.1,0.25,0.5,1'. Raising a width is "
            "MORE permissive, so regression coverage is non-decreasing along "
            "this axis. It is a separate surface from the classification "
            "confidence grid and is never derived from it. Omit it to report "
            "the operating point only."
        ),
    )
    parser.add_argument(
        "--estimate-threshold",
        action="store_true",
        help=(
            "Estimate the population threshold on each fold's calibration "
            "groups. Never reads an outer-test label."
        ),
    )
    parser.add_argument(
        "--no-personalized-thresholds",
        action="store_true",
        help="Apply the population threshold to every subject.",
    )
    parser.add_argument(
        "--calibration",
        type=str,
        default="sigmoid",
        choices=["none", "sigmoid", "isotonic"],
    )
    parser.add_argument("--calibration-group-fraction", type=float, default=0.25)
    parser.add_argument("--calibration-bins", type=int, default=10)


def run_uncertainty_demo(args: argparse.Namespace) -> int:
    """Report uncertainty and selective prediction as a software self-check."""
    return _run_uncertainty(args, mode=EvaluationMode.SOFTWARE_SELF_CHECK)


def run_uncertainty_train(args: argparse.Namespace) -> int:
    """Report uncertainty and selective prediction in the requested mode."""
    mode = (
        EvaluationMode.SCIENTIFIC
        if getattr(args, "mode", "self-check") == "scientific"
        else EvaluationMode.SOFTWARE_SELF_CHECK
    )
    return _run_uncertainty(args, mode=mode)


def _run_uncertainty(args: argparse.Namespace, *, mode: EvaluationMode) -> int:
    from pydantic import ValidationError

    from engagevr.config import load_config
    from engagevr.features.assembly import DatasetAssemblyError
    from engagevr.features.validation import DatasetValidationError, LeakageError
    from engagevr.training.artifacts import ArtifactError
    from engagevr.training.calibration import CalibrationError, CalibrationMethod
    from engagevr.training.fusion import FusionError
    from engagevr.training.models import UnsupportedModelError
    from engagevr.training.personalization import PersonalizationError
    from engagevr.training.preprocessing import PreprocessingError
    from engagevr.training.runner import EvaluationError, ScientificModeError
    from engagevr.training.splits import GroupOverlapError, SplitConfigurationError
    from engagevr.training.uncertainty import UncertaintyError
    from engagevr.training.uncertainty_runner import (
        UncertaintyConfigurationError,
        UncertaintyRunConfiguration,
        run_uncertainty,
    )

    dataset = Path(args.dataset)
    if not dataset.exists():
        print(
            f"Error: dataset {dataset} does not exist. Build one first with "
            "'features-demo', or pass --dataset.",
            file=sys.stderr,
        )
        return 2
    if args.folds < 2:
        print(
            f"Error: --folds must be at least 2; got {args.folds}. A single "
            "fold has no held-out portion.",
            file=sys.stderr,
        )
        return 2
    if args.threshold is not None and not 0.0 <= args.threshold <= 1.0:
        print(
            f"Error: --threshold must lie in [0, 1]; got {args.threshold}. A "
            "confidence threshold is compared against a probability.",
            file=sys.stderr,
        )
        return 2
    if args.alpha is not None and not 0.0 < args.alpha < 1.0:
        print(
            f"Error: --alpha must lie strictly between 0 and 1; got "
            f"{args.alpha}. alpha is a nominal miscoverage rate, so alpha=0 "
            "would demand an infinite interval and alpha=1 an empty one.",
            file=sys.stderr,
        )
        return 2
    if args.maximum_interval_width is not None and args.maximum_interval_width <= 0.0:
        print(
            "Error: --maximum-interval-width must be positive; got "
            f"{args.maximum_interval_width}. A non-positive maximum would "
            "abstain on every window.",
            file=sys.stderr,
        )
        return 2

    width_grid: list[float] | None = None
    if getattr(args, "interval_width_grid", None) is not None:
        raw = str(args.interval_width_grid)
        entries = [part.strip() for part in raw.split(",") if part.strip()]
        if not entries:
            print(
                "Error: --interval-width-grid is empty. Give at least one "
                "width, or omit the option to report the operating point only.",
                file=sys.stderr,
            )
            return 2
        width_grid = []
        for entry in entries:
            try:
                width = float(entry)
            except ValueError:
                print(
                    f"Error: --interval-width-grid entry {entry!r} is not a "
                    "number. Widths are given in the target's own units.",
                    file=sys.stderr,
                )
                return 2
            if not math.isfinite(width) or width < 0.0:
                print(
                    f"Error: --interval-width-grid entry {entry!r} is not a "
                    "finite non-negative width. An interval width is a "
                    "distance, so it cannot be negative.",
                    file=sys.stderr,
                )
                return 2
            width_grid.append(width)
        if len(set(width_grid)) != len(width_grid):
            print(
                "Error: --interval-width-grid repeats a width; each sweep "
                "point must appear once.",
                file=sys.stderr,
            )
            return 2

    try:
        target = TargetName(args.target)
    except ValueError:
        supported = ", ".join(t.value for t in TargetName)
        print(
            f"Error: unsupported target {args.target!r}; supported: {supported}",
            file=sys.stderr,
        )
        return 2

    settings = load_config()
    try:
        configuration = settings.uncertainty.resolve(
            prediction_source=(
                args.source.replace("-", "_") if args.source is not None else None
            ),
            population_confidence_threshold=args.threshold,
            alpha=args.alpha,
            maximum_interval_width=args.maximum_interval_width,
            interval_width_grid=width_grid,
            estimate_population_threshold=(True if args.estimate_threshold else None),
            personalized_thresholds_enabled=(
                False if args.no_personalized_thresholds else None
            ),
        )
    except (ValidationError, ValueError) as exc:
        print(f"Error: invalid uncertainty configuration: {exc}", file=sys.stderr)
        return 2

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    config = UncertaintyRunConfiguration(
        dataset_path=dataset,
        target_name=target,
        output_directory=output,
        selective=configuration,
        evaluation_mode=mode,
        n_splits=args.folds,
        random_seed=args.seed,
        calibration_method=CalibrationMethod(args.calibration),
        calibration_group_fraction=args.calibration_group_fraction,
        calibration_bins=args.calibration_bins,
    )

    if mode is EvaluationMode.SOFTWARE_SELF_CHECK:
        print(SOFTWARE_SELF_CHECK_BANNER)
        print(_SYNTHETIC_BANNER)
        print()

    try:
        result = run_uncertainty(config)
    except ScientificModeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 3
    except (
        SplitConfigurationError,
        GroupOverlapError,
        LeakageError,
        UnsupportedModelError,
        UnsupportedTargetError,
        CalibrationError,
        PreprocessingError,
        DatasetValidationError,
        DatasetAssemblyError,
        ArtifactError,
        UncertaintyConfigurationError,
        UncertaintyError,
        PersonalizationError,
        FusionError,
        EvaluationError,
    ) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    _print_uncertainty_result(result, config)
    return 0


def _print_uncertainty_result(result: object, config: object) -> None:
    from engagevr.schemas.targets import TaskType
    from engagevr.training.uncertainty_runner import (
        UncertaintyRunConfiguration,
        UncertaintyRunResult,
    )

    assert isinstance(result, UncertaintyRunResult)
    assert isinstance(config, UncertaintyRunConfiguration)
    evaluation = result.uncertainty
    settings = evaluation.configuration
    classification = evaluation.task_type is TaskType.CLASSIFICATION
    folds = [fold for fold in evaluation.folds if fold.evaluated]

    print(f"Run id:                        {result.run_id}")
    print(f"Experiment directory:          {result.directory}")
    print(f"Dataset:                       {config.dataset_path}")
    print(f"Dataset fingerprint:           {evaluation.dataset_fingerprint}")
    print(f"Split fingerprint:             {evaluation.split_manifest_fingerprint}")
    print(f"Target:                        {evaluation.target_name}")
    print(f"Task type:                     {evaluation.task_type.value}")
    print(f"Source prediction model:       {settings.prediction_source.value}")
    print(
        "Source estimator:              "
        + (
            settings.model_classification
            if classification
            else settings.model_regression
        )
    )
    print(f"Group field:                   {evaluation.group_field}")
    print(f"Independent groups:            {evaluation.group_count}")
    print(f"Outer folds:                   {evaluation.fold_count}")
    print(f"Split audit passed:            {result.splits.audit_passed}")
    print(f"Random seed:                   {evaluation.random_seed}")

    if classification:
        statuses = {fold.probability_calibration_status.value for fold in folds}
        print(
            f"Probability calibration:       {config.calibration_method.value} "
            f"({', '.join(sorted(statuses)) or 'none'})"
        )
        print(f"Confidence definition:         {settings.confidence_source.value}")
        print("Confidence equation:           " + settings.confidence_equation)
        print(
            "Population threshold:          "
            f"{settings.population_confidence_threshold} "
            "(ENGINEERING DEFAULT, not an optimum)"
        )
        sources = {
            fold.applied_population_threshold_source.value
            for fold in folds
            if fold.applied_population_threshold_source
        }
        print("Threshold source:              " + (", ".join(sorted(sources)) or "n/a"))
        print(
            "Personalized thresholds:       "
            + (
                f"applied to {evaluation.personalized_subject_count} subject-fold(s), "
                f"{evaluation.population_fallback_subject_count} fell back"
                if settings.personalized_thresholds_enabled
                else "disabled; the population threshold applies to every subject"
            )
        )
    else:
        print(f"Interval method:               {settings.interval_method.value}")
        print("Conformal rule:                " + settings.conformal_equation)
        print(f"Nominal miscoverage alpha:     {settings.alpha}")
        print(f"Nominal coverage:              {1.0 - settings.alpha}")
        print(
            "Maximum interval width:        "
            + (
                str(settings.maximum_interval_width)
                if settings.maximum_interval_width is not None
                else "not configured; no width-based abstention"
            )
        )
        print(
            "Interval-width grid:           "
            + (
                ", ".join(f"{w:g}" for w in settings.interval_width_grid)
                + "  (target units; higher is MORE permissive)"
                if settings.interval_width_grid
                else "not configured; no width sweep is evaluated and no "
                "coverage curve is manufactured from the confidence grid"
            )
        )
        available = [fold for fold in folds if fold.conformal_available]
        print(
            "Conformal quantile per fold:   "
            + (
                ", ".join(
                    f"fold {fold.fold_index}="
                    f"{fold.conformal_quantile:.4f} (k={fold.conformal_order_statistic}"
                    f"/n={fold.conformal_calibration_sample_count})"
                    for fold in available
                )
                or "none available"
            )
        )
        print(
            "Personalized thresholds:       a confidence threshold has no "
            "meaning for a point prediction; not applied"
        )

    print(
        "Calibration groups per fold:   "
        + ", ".join(
            f"fold {fold.fold_index}="
            + str(
                len(
                    fold.probability_calibration_group_ids
                    or fold.conformal_calibration_group_ids
                )
            )
            for fold in folds
        )
    )
    print(f"Evaluated windows:             {evaluation.total_window_count}")
    print(f"Accepted:                      {evaluation.accepted_count}")
    print(f"Abstained:                     {evaluation.abstained_count}")
    print(f"Prediction unavailable:        {evaluation.unavailable_count}")
    print(
        "Selective coverage:            "
        + (
            f"{evaluation.coverage:.4f}"
            if evaluation.coverage is not None
            else "unavailable"
        )
        + "  (accepted / every evaluated window)"
    )
    print(
        "Abstention rate:               "
        + (
            f"{evaluation.abstention_rate:.4f}"
            if evaluation.abstention_rate is not None
            else "unavailable"
        )
    )
    if evaluation.abstention_reason_counts:
        print("Abstention reasons:")
        for reason, count in evaluation.abstention_reason_counts.items():
            print(f"  {reason:<40} {count}")
    else:
        print("Abstention reasons:            none recorded")

    curve = result.coverage_curve
    print(f"Coverage curve x-axis:         {curve.axis.value}")
    print(f"Coverage curve x-axis units:   {curve.axis_units}")
    if curve.points:
        print(
            "Coverage curve:                "
            + ", ".join(
                f"{point.coverage_point.threshold:g}:"
                f"{point.coverage_point.coverage:.3f}"
                for point in curve.points
            )
        )
        print(
            f"Coverage {curve.expected_monotonic_direction.value:<15}"
            f"       {curve.coverage_is_monotonic}"
        )
        print("Monotonicity rule:             " + curve.monotonicity_rule)
    else:
        print(
            "Coverage curve:                not evaluated — "
            + str(curve.points_unavailable_reason)
        )
    print(
        "Area under risk-coverage:      "
        + (
            f"{curve.area_under_risk_coverage:.4f} (descriptive only)"
            if curve.area_under_risk_coverage is not None
            else f"unavailable — {curve.area_under_risk_coverage_unavailable_reason}"
        )
    )
    print(
        "Adaptation gate:               "
        f"{evaluation.adaptation_gate_eligible_count} eligible, "
        f"{evaluation.adaptation_gate_blocked_count} blocked"
    )

    print()
    print(f"Metrics:                       {result.directory / 'metrics.json'}")
    print(
        f"Selective metrics:             {result.directory / 'selective_metrics.json'}"
    )
    print(f"Coverage curve:                {result.directory / 'coverage_curve.json'}")
    print(f"Thresholds:                    {result.directory / 'thresholds.json'}")
    print(
        f"Adaptation gate:               {result.directory / 'adaptation_gate.parquet'}"
    )
    print(f"Manifest:                      {result.directory / 'manifest.json'}")
    print(
        "scientific_evaluation_eligible="
        f"{str(evaluation.scientific_evaluation_eligible).lower()}"
    )

    for warning in result.warnings:
        print(f"Warning: {warning}")

    print()
    print(_UNCERTAINTY_NOTE)
    print()
    print(_GATE_NOTE)
    print()
    print(_PERMANENT_DISCLAIMER)
    if evaluation.evaluation_mode is EvaluationMode.SOFTWARE_SELF_CHECK:
        print()
        print(SOFTWARE_SELF_CHECK_BANNER)


__all__ = [
    "add_parsers",
    "run_uncertainty_demo",
    "run_uncertainty_train",
]
