"""Milestone 6 CLI: fusion and personalization commands.

``fusion-demo`` / ``fusion-train`` evaluate multimodal fusion;
``personalization-demo`` / ``personalization-train`` report a population
baseline and a personalized result separately over identical evaluation
windows.

Kept in its own module so ``__main__`` stays a thin dispatcher and so the
Milestone 6 commands can be tested without importing the webcam, rPPG, or
WebSocket code paths.

The ``*-demo`` commands operate on SYNTHETIC data and print a permanent
disclaimer.  ``*-train --mode scientific`` refuses any dataset whose
predictors or targets are synthetic, whose target provenance is unstated,
or which asks for synthetic modality dropout.

No command in this module prints a "winner", a "best fusion model", a
claim that personalization helped, or a number that describes a person.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from engagevr.schemas.experiments import SOFTWARE_SELF_CHECK_BANNER, EvaluationMode
from engagevr.schemas.fusion import FusionModality, FusionStrategy
from engagevr.schemas.personalization import REQUESTABLE_METHODS
from engagevr.schemas.targets import TargetName, UnsupportedTargetError

#: Printed by every command in this module.
_PERMANENT_DISCLAIMER = (
    "EngageVR produces ESTIMATES from software measurements. Nothing here is "
    "a medical, diagnostic, psychological, or clinical conclusion, and no "
    "number printed by these commands is experimental evidence about any "
    "person."
)

_SYNTHETIC_BANNER = (
    "=== SYNTHETIC DATA ===\n"
    "Every row and every target below was generated by software from a known\n"
    "latent process. No person was recorded. No metric computed from this\n"
    "data is model accuracy, engagement validity, cognitive-load validity, or\n"
    "evidence of any kind, and none may be compared with a published result\n"
    "on real data."
)

_FUSION_NOTE = (
    "Fusion strategies below were evaluated on identical grouped outer folds. "
    "No strategy is a champion, none is validated, and a comparison computed "
    "on synthetic data cannot select a best fusion architecture: it would "
    "describe this repository's own generator, not any person."
)

_PERSONALIZATION_NOTE = (
    "Population and personalized software-check results are reported "
    "separately over identical evaluation windows. Synthetic differences "
    "are not evidence of a personalization benefit. No personalized model "
    "here is validated, none is a champion, and none has been fitted to a "
    "real participant label."
)

_STRATEGY_CHOICES = sorted(
    {s.value for s in FusionStrategy}
    | {s.value.replace("_", "-") for s in FusionStrategy}
)

_METHOD_CHOICES = sorted(
    {m.value for m in REQUESTABLE_METHODS}
    | {m.value.replace("_", "-") for m in REQUESTABLE_METHODS}
)


def add_parsers(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the Milestone 6 subcommands on an existing subparser set."""
    demo = sub.add_parser(
        "fusion-demo",
        help="Run multimodal-fusion software verification on a SYNTHETIC dataset.",
    )
    _add_fusion_arguments(demo)
    demo.add_argument(
        "--output", type=str, default="artifacts/experiments/m6-fusion-demo"
    )

    train = sub.add_parser(
        "fusion-train",
        help="Fit and evaluate multimodal fusion on a windowed-feature dataset.",
    )
    _add_fusion_arguments(train)
    train.add_argument(
        "--mode",
        type=str,
        default="self-check",
        choices=["self-check", "scientific"],
        help="Scientific mode rejects synthetic predictors, targets, or dropout.",
    )
    train.add_argument("--output", type=str, default="artifacts/experiments/fusion-run")

    personalization_demo = sub.add_parser(
        "personalization-demo",
        help=(
            "Report population and personalized baselines separately on a "
            "SYNTHETIC dataset."
        ),
    )
    _add_personalization_arguments(personalization_demo)
    personalization_demo.add_argument(
        "--output",
        type=str,
        default="artifacts/experiments/m6-personalization-demo",
    )

    personalization_train = sub.add_parser(
        "personalization-train",
        help=(
            "Fit a population model and a personalized variant on a "
            "windowed-feature dataset."
        ),
    )
    _add_personalization_arguments(personalization_train)
    personalization_train.add_argument(
        "--mode",
        type=str,
        default="self-check",
        choices=["self-check", "scientific"],
        help="Scientific mode rejects synthetic predictors or targets.",
    )
    personalization_train.add_argument(
        "--output", type=str, default="artifacts/experiments/personalization-run"
    )


def _add_personalization_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dataset", type=str, default="artifacts/datasets/m5-synthetic.parquet"
    )
    parser.add_argument(
        "--target",
        type=str,
        default=TargetName.ENGAGEMENT_CLASS.value,
        choices=[t.value for t in TargetName],
    )
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--method",
        type=str,
        default=None,
        choices=_METHOD_CHOICES,
        help=(
            "Personalization method. 'cold-start' is an outcome, not a "
            "method: request it with --calibration-windows 0."
        ),
    )
    parser.add_argument(
        "--modalities",
        type=str,
        nargs="+",
        default=None,
        choices=[m.value for m in FusionModality],
        help=(
            "Measurement modality groups feeding the fused population model. "
            "'quality' is not a modality and is not accepted here."
        ),
    )
    parser.add_argument(
        "--calibration-windows",
        type=int,
        default=None,
        help=(
            "Earliest windows per held-out subject reserved for personal "
            "calibration. 0 requests cold-start mode."
        ),
    )
    parser.add_argument("--minimum-calibration-windows", type=int, default=None)
    parser.add_argument("--minimum-evaluation-windows", type=int, default=None)
    parser.add_argument(
        "--calibration",
        type=str,
        default="sigmoid",
        choices=["none", "sigmoid", "isotonic"],
        help="Probability calibration of the POPULATION model, not of a person.",
    )
    parser.add_argument("--calibration-group-fraction", type=float, default=0.25)
    parser.add_argument("--calibration-bins", type=int, default=10)


def _add_fusion_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dataset", type=str, default="artifacts/datasets/m5-synthetic.parquet"
    )
    parser.add_argument(
        "--target",
        type=str,
        default=TargetName.ENGAGEMENT_CLASS.value,
        choices=[t.value for t in TargetName],
    )
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--strategies",
        type=str,
        nargs="+",
        default=None,
        choices=_STRATEGY_CHOICES,
        help="Fusion strategies to evaluate. Default: the configured set.",
    )
    parser.add_argument(
        "--modalities",
        type=str,
        nargs="+",
        default=None,
        choices=[m.value for m in FusionModality],
        help=(
            "Measurement modality groups. 'quality' is not a modality and is "
            "not accepted here."
        ),
    )
    parser.add_argument("--minimum-modalities", type=int, default=None)
    parser.add_argument(
        "--calibration",
        type=str,
        default="sigmoid",
        choices=["none", "sigmoid", "isotonic"],
    )
    parser.add_argument("--calibration-group-fraction", type=float, default=0.25)
    parser.add_argument("--calibration-bins", type=int, default=10)
    parser.add_argument(
        "--no-calibrated-experts",
        action="store_true",
        help="Fuse uncalibrated expert probabilities.",
    )
    parser.add_argument(
        "--scenarios",
        type=str,
        nargs="+",
        default=None,
        help="Missing-modality scenarios. Default: every defined scenario.",
    )
    parser.add_argument(
        "--no-robustness",
        action="store_true",
        help="Evaluate the reference scenario only.",
    )
    parser.add_argument(
        "--synthetic-dropout",
        type=float,
        default=None,
        help=(
            "Per-window per-modality dropout probability for a software "
            "robustness check. Refused in scientific mode."
        ),
    )
    parser.add_argument("--dropout-seed", type=int, default=None)


def run_fusion_demo(args: argparse.Namespace) -> int:
    """Run the fusion pipeline as a software self-check."""
    return _run_fusion(args, mode=EvaluationMode.SOFTWARE_SELF_CHECK)


def run_fusion_train(args: argparse.Namespace) -> int:
    """Run the fusion pipeline in the requested evaluation mode."""
    mode = (
        EvaluationMode.SCIENTIFIC
        if getattr(args, "mode", "self-check") == "scientific"
        else EvaluationMode.SOFTWARE_SELF_CHECK
    )
    return _run_fusion(args, mode=mode)


def _run_fusion(args: argparse.Namespace, *, mode: EvaluationMode) -> int:
    from pydantic import ValidationError

    from engagevr.config import load_config
    from engagevr.features.assembly import DatasetAssemblyError
    from engagevr.features.validation import DatasetValidationError, LeakageError
    from engagevr.training.artifacts import ArtifactError
    from engagevr.training.calibration import CalibrationError, CalibrationMethod
    from engagevr.training.fusion import FusionError
    from engagevr.training.fusion_runner import (
        FusionConfigurationError,
        FusionRunConfiguration,
        run_fusion,
    )
    from engagevr.training.models import UnsupportedModelError
    from engagevr.training.preprocessing import PreprocessingError
    from engagevr.training.robustness import RobustnessError
    from engagevr.training.runner import EvaluationError, ScientificModeError
    from engagevr.training.splits import GroupOverlapError, SplitConfigurationError
    from engagevr.training.stacking import StackingError

    dataset = Path(args.dataset)
    if not dataset.exists():
        print(
            f"Error: dataset {dataset} does not exist. Build one first with "
            "'features-demo', or pass --dataset.",
            file=sys.stderr,
        )
        return 2
    if args.folds < 2:
        print(
            f"Error: --folds must be at least 2; got {args.folds}. A single "
            "fold has no held-out portion.",
            file=sys.stderr,
        )
        return 2

    try:
        target = TargetName(args.target)
    except ValueError:
        supported = ", ".join(t.value for t in TargetName)
        print(
            f"Error: unsupported target {args.target!r}; supported: {supported}",
            file=sys.stderr,
        )
        return 2

    settings = load_config()
    try:
        fusion_configuration = settings.fusion.resolve(
            strategies=args.strategies,
            modalities=args.modalities,
            minimum_modalities=args.minimum_modalities,
            use_calibrated_experts=(False if args.no_calibrated_experts else None),
            scenarios=([] if args.no_robustness else args.scenarios),
            synthetic_dropout_probability=args.synthetic_dropout,
            synthetic_dropout_seed=args.dropout_seed,
        )
        if args.no_robustness:
            fusion_configuration = fusion_configuration.model_copy(
                update={
                    "robustness": fusion_configuration.robustness.model_copy(
                        update={"enabled": False}
                    )
                }
            )
    except (ValidationError, ValueError) as exc:
        print(f"Error: invalid fusion configuration: {exc}", file=sys.stderr)
        return 2

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    config = FusionRunConfiguration(
        dataset_path=dataset,
        target_name=target,
        output_directory=output,
        fusion=fusion_configuration,
        evaluation_mode=mode,
        n_splits=args.folds,
        random_seed=args.seed,
        calibration_method=CalibrationMethod(args.calibration),
        calibration_group_fraction=args.calibration_group_fraction,
        calibration_bins=args.calibration_bins,
    )

    if mode is EvaluationMode.SOFTWARE_SELF_CHECK:
        print(SOFTWARE_SELF_CHECK_BANNER)
        print(_SYNTHETIC_BANNER)
        print()

    try:
        result = run_fusion(config)
    except ScientificModeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 3
    except (
        SplitConfigurationError,
        GroupOverlapError,
        LeakageError,
        UnsupportedModelError,
        UnsupportedTargetError,
        CalibrationError,
        PreprocessingError,
        DatasetValidationError,
        DatasetAssemblyError,
        ArtifactError,
        FusionConfigurationError,
        FusionError,
        RobustnessError,
        StackingError,
        EvaluationError,
    ) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    _print_result(result, config)
    return 0


def _print_result(result: object, config: object) -> None:
    from engagevr.training.fusion_runner import FusionRunConfiguration, FusionRunResult

    assert isinstance(result, FusionRunResult)
    assert isinstance(config, FusionRunConfiguration)
    fusion = config.fusion
    metrics = result.metrics
    evaluation = result.fusion_metrics

    print(f"Run id:                 {result.run_id}")
    print(f"Experiment directory:   {result.directory}")
    print(f"Dataset:                {config.dataset_path}")
    print(f"Dataset fingerprint:    {evaluation.dataset_fingerprint}")
    print(f"Split fingerprint:      {evaluation.split_manifest_fingerprint}")
    print(f"Target:                 {evaluation.target_name}")
    print(f"Task type:              {evaluation.task_type.value}")
    print(f"Group field:            {evaluation.group_field}")
    print(f"Independent groups:     {evaluation.group_count}")
    print(f"Folds:                  {evaluation.fold_count}")
    print(f"Split strategy:         {result.splits.strategy.value}")
    print(f"Split audit passed:     {result.splits.audit_passed}")
    print(f"Random seed:            {evaluation.random_seed}")
    print(
        "Modality groups:        " + ", ".join(m.value for m in evaluation.modalities)
    )
    print(
        "Strategies:             "
        + ", ".join(s.strategy.value for s in evaluation.strategies)
    )
    print(f"Minimum modalities:     {fusion.minimum_modalities}")
    print(
        "Expert estimator:       "
        f"{fusion.expert_model_classification} (classification) / "
        f"{fusion.expert_model_regression} (regression)"
    )
    print(f"Calibration method:     {config.calibration_method.value}")
    print(f"Calibrated experts:     {fusion.use_calibrated_experts}")
    print("Calibration placement:  per expert, before fusion; none after fusion")
    print(f"Quality weighting:      enabled={fusion.quality.enabled}")
    print(
        "  missing-quality:      "
        f"{fusion.quality.missing_quality_policy.value} "
        f"(fallback {fusion.quality.missing_quality_fallback})"
    )
    print(
        "  minimum quality:      "
        f"{fusion.quality.minimum_quality}; minimum effective weight "
        f"{fusion.quality.minimum_effective_weight}"
    )
    print(
        "  base weights:         "
        + (
            "deterministic equal weights (control)"
            if not fusion.quality.base_weights
            else str(dict(sorted(fusion.quality.base_weights.items())))
        )
    )
    print(f"Stacking:               enabled={fusion.stacking.enabled}")
    print("Robustness scenarios:   " + ", ".join(s.name for s in result.scenarios))
    print(
        "Synthetic dropout:      "
        + (
            f"seed={result.robustness.synthetic_dropout_seed}, "
            f"probability={result.robustness.synthetic_dropout_probability}"
            if result.robustness.synthetic_dropout_applied
            else "not applied"
        )
    )
    print(f"Evaluation mode:        {metrics.evaluation_mode.value}")
    print(f"Scientific evaluation:  {metrics.scientific_evaluation_eligible}")
    print()

    print("Fusion strategies (identical outer folds, fold-local preprocessing):")
    for strategy in evaluation.strategies:
        print(f"  {strategy.strategy.value}")
        for aggregate in strategy.aggregate:
            if aggregate.mean is None:
                print(
                    f"    {aggregate.name:<38} unavailable "
                    f"({aggregate.unavailable_reason})"
                )
            else:
                print(
                    f"    {aggregate.name:<38} {aggregate.mean:.4f} +/- "
                    f"{aggregate.standard_deviation:.4f} "
                    f"({aggregate.valid_fold_count}/{aggregate.total_fold_count} folds)"
                )
        for aggregate in strategy.fusion_aggregate:
            if aggregate.name.startswith(
                ("fusion.coverage", "fusion.mean_available_expert_count")
            ):
                value = (
                    "unavailable" if aggregate.mean is None else f"{aggregate.mean:.4f}"
                )
                print(f"    {aggregate.name:<38} {value}")
    print()

    if evaluation.unimodal_control is not None:
        control = evaluation.unimodal_control
        value = (
            "unavailable"
            if control.aggregate is None or control.aggregate.mean is None
            else f"{control.aggregate.mean:.4f}"
        )
        print(
            f"Descriptive unimodal control ({control.metric_name}): {value} "
            f"across folds"
        )
        print(f"  per-fold best modality: {control.per_fold_modality}")
        print(f"  {control.note}")
        print()

    print("Missing-modality robustness (coverage = fused / evaluated windows):")
    for entry in result.robustness.results:
        if not entry.evaluated:
            print(
                f"  {entry.scenario_name:<28} {entry.strategy.value:<24} "
                f"not evaluated: {entry.unavailable_reason}"
            )
            continue
        coverage = "unavailable" if entry.coverage is None else f"{entry.coverage:.3f}"
        print(
            f"  {entry.scenario_name:<28} {entry.strategy.value:<24} "
            f"coverage={coverage} fused={entry.fused_window_count} "
            f"unavailable={entry.unavailable_fusion_count}"
        )
    print()

    if result.warnings:
        print("Warnings:")
        for warning in result.warnings:
            print(f"  {warning}")
        print()

    print(f"Metrics:                {result.directory / 'metrics.json'}")
    print(f"Fusion metrics:         {result.directory / 'fusion_metrics.json'}")
    print(f"Fusion config:          {result.directory / 'fusion_config.json'}")
    print(f"Experts:                {result.directory / 'experts.json'}")
    print(f"Robustness:             {result.directory / 'robustness.json'}")
    print(f"Calibration:            {result.directory / 'calibration.json'}")
    print(f"Splits:                 {result.directory / 'splits.json'}")
    print(f"Predictions:            {result.directory / 'predictions.parquet'}")
    print(f"Expert predictions:     {result.directory / 'expert_predictions.parquet'}")
    print(f"Fusion weights:         {result.directory / 'fusion_weights.parquet'}")
    print(f"Manifest:               {result.directory / 'manifest.json'}")
    print()
    if metrics.evaluation_mode.value == "software_self_check":
        print(SOFTWARE_SELF_CHECK_BANNER)
    for disclaimer in metrics.disclaimers:
        print(disclaimer)
    print(_FUSION_NOTE)
    print(_PERMANENT_DISCLAIMER)
    print(
        "Expert disagreement recorded here is an ensemble-disagreement "
        "diagnostic, not an uncertainty estimate, and it does not trigger "
        "abstention; uncertainty-aware inference is Milestone 7."
    )
    print(
        "No fusion strategy here is a champion, none is production-ready, and "
        "none has been evaluated against real participant labels."
    )


def run_personalization_demo(args: argparse.Namespace) -> int:
    """Report population and personalized baselines as a software self-check."""
    return _run_personalization(args, mode=EvaluationMode.SOFTWARE_SELF_CHECK)


def run_personalization_train(args: argparse.Namespace) -> int:
    """Report population and personalized baselines in the requested mode."""
    mode = (
        EvaluationMode.SCIENTIFIC
        if getattr(args, "mode", "self-check") == "scientific"
        else EvaluationMode.SOFTWARE_SELF_CHECK
    )
    return _run_personalization(args, mode=mode)


def _run_personalization(args: argparse.Namespace, *, mode: EvaluationMode) -> int:
    from pydantic import ValidationError

    from engagevr.config import load_config
    from engagevr.features.assembly import DatasetAssemblyError
    from engagevr.features.validation import DatasetValidationError, LeakageError
    from engagevr.training.artifacts import ArtifactError
    from engagevr.training.calibration import CalibrationError, CalibrationMethod
    from engagevr.training.fusion import FusionError
    from engagevr.training.models import UnsupportedModelError
    from engagevr.training.personalization import PersonalizationError
    from engagevr.training.personalization_runner import (
        PersonalizationConfigurationError,
        PersonalizationRunConfiguration,
        run_personalization,
    )
    from engagevr.training.preprocessing import PreprocessingError
    from engagevr.training.runner import EvaluationError, ScientificModeError
    from engagevr.training.splits import GroupOverlapError, SplitConfigurationError

    dataset = Path(args.dataset)
    if not dataset.exists():
        print(
            f"Error: dataset {dataset} does not exist. Build one first with "
            "'features-demo', or pass --dataset.",
            file=sys.stderr,
        )
        return 2
    if args.folds < 2:
        print(
            f"Error: --folds must be at least 2; got {args.folds}. A single "
            "fold has no held-out portion.",
            file=sys.stderr,
        )
        return 2
    if args.calibration_windows is not None and args.calibration_windows < 0:
        print(
            "Error: --calibration-windows cannot be negative; use 0 to request "
            "cold-start mode.",
            file=sys.stderr,
        )
        return 2

    try:
        target = TargetName(args.target)
    except ValueError:
        supported = ", ".join(t.value for t in TargetName)
        print(
            f"Error: unsupported target {args.target!r}; supported: {supported}",
            file=sys.stderr,
        )
        return 2

    settings = load_config()
    try:
        configuration = settings.personalization.resolve(
            method=args.method,
            modalities=args.modalities,
            calibration_windows=args.calibration_windows,
            minimum_calibration_windows=args.minimum_calibration_windows,
            minimum_evaluation_windows=args.minimum_evaluation_windows,
        )
    except (ValidationError, ValueError) as exc:
        print(f"Error: invalid personalization configuration: {exc}", file=sys.stderr)
        return 2

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    config = PersonalizationRunConfiguration(
        dataset_path=dataset,
        target_name=target,
        output_directory=output,
        personalization=configuration,
        evaluation_mode=mode,
        n_splits=args.folds,
        random_seed=args.seed,
        calibration_method=CalibrationMethod(args.calibration),
        calibration_group_fraction=args.calibration_group_fraction,
        calibration_bins=args.calibration_bins,
    )

    if mode is EvaluationMode.SOFTWARE_SELF_CHECK:
        print(SOFTWARE_SELF_CHECK_BANNER)
        print(_SYNTHETIC_BANNER)
        print()

    try:
        result = run_personalization(config)
    except ScientificModeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 3
    except (
        SplitConfigurationError,
        GroupOverlapError,
        LeakageError,
        UnsupportedModelError,
        UnsupportedTargetError,
        CalibrationError,
        PreprocessingError,
        DatasetValidationError,
        DatasetAssemblyError,
        ArtifactError,
        PersonalizationConfigurationError,
        PersonalizationError,
        FusionError,
        EvaluationError,
    ) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    _print_personalization_result(result, config)
    return 0


def _print_personalization_result(result: object, config: object) -> None:
    from engagevr.training.personalization_runner import (
        PersonalizationRunConfiguration,
        PersonalizationRunResult,
    )

    assert isinstance(result, PersonalizationRunResult)
    assert isinstance(config, PersonalizationRunConfiguration)
    evaluation = result.personalization
    settings = evaluation.configuration
    metrics = result.metrics
    folds = [fold for fold in evaluation.folds if fold.evaluated]

    print(f"Run id:                        {result.run_id}")
    print(f"Experiment directory:          {result.directory}")
    print(f"Dataset:                       {config.dataset_path}")
    print(f"Dataset fingerprint:           {evaluation.dataset_fingerprint}")
    print(f"Split fingerprint:             {evaluation.split_manifest_fingerprint}")
    print(f"Target:                        {evaluation.target_name}")
    print(f"Task type:                     {evaluation.task_type.value}")
    print(f"Group field:                   {evaluation.group_field}")
    print(f"Independent groups:            {evaluation.group_count}")
    print(f"Folds:                         {evaluation.fold_count}")
    print(f"Split audit passed:            {result.splits.audit_passed}")
    print(f"Random seed:                   {evaluation.random_seed}")
    print(f"Personalization method:        {settings.method.value}")
    print(
        "Modality groups:               "
        + ", ".join(m.value for m in settings.modalities)
    )
    print(
        f"Population estimator:          {_population_estimator(settings, evaluation)}"
    )
    print(f"Probability calibration:       {config.calibration_method.value}")
    print(
        "Population training subjects:  "
        + ", ".join(
            f"fold {fold.fold_index}={fold.population_training_subject_count}"
            for fold in folds
        )
    )
    print(
        "Held-out subjects:             "
        + ", ".join(
            f"fold {fold.fold_index}={fold.held_out_subject_count}" for fold in folds
        )
    )
    print(f"Calibration windows:           {evaluation.total_calibration_window_count}")
    print(f"Evaluation windows:            {evaluation.total_evaluation_window_count}")
    print(
        "Excluded boundary windows:     "
        f"{evaluation.total_excluded_overlap_window_count}"
    )
    print(f"Personalized subject-folds:    {evaluation.personalized_subject_count}")
    print(f"Cold-start subject-folds:      {evaluation.cold_start_subject_count}")
    print(
        f"Unavailable personalization:   {evaluation.unavailable_personalization_count}"
    )
    coverage = (
        "unavailable"
        if evaluation.personalization_coverage is None
        else f"{evaluation.personalization_coverage:.3f}"
    )
    print(f"Personalization coverage:      {coverage}")
    print(f"Evaluation mode:               {metrics.evaluation_mode.value}")
    print(
        "Scientific evaluation:         "
        f"scientific_evaluation_eligible={metrics.scientific_evaluation_eligible}"
    )
    print()

    print("Population baseline (identical evaluation windows):")
    _print_aggregates(evaluation.population_aggregate)
    print()
    print("Personalized (identical evaluation windows):")
    _print_aggregates(evaluation.personalized_aggregate)
    print()

    if result.warnings:
        print("Warnings:")
        for warning in result.warnings:
            print(f"  {warning}")
        print()

    print(f"Population metrics:            {result.directory / 'metrics.json'}")
    print("  JSON pointer:                /results/0  (model_name='population')")
    print(f"Personalized metrics:          {result.directory / 'metrics.json'}")
    print("  JSON pointer:                /results/1  (model_name='personalized')")
    print(f"Personalization document:      {result.directory / 'personalization.json'}")
    print(
        f"Personal baselines:            {result.directory / 'personal_baselines.json'}"
    )
    configuration_path = result.directory / "personalization_config.json"
    print(f"Configuration:                 {configuration_path}")
    print(f"Calibration:                   {result.directory / 'calibration.json'}")
    print(f"Splits:                        {result.directory / 'splits.json'}")
    print(f"Predictions:                   {result.directory / 'predictions.parquet'}")
    print(f"Manifest:                      {result.directory / 'manifest.json'}")
    print()
    if metrics.evaluation_mode.value == "software_self_check":
        print(SOFTWARE_SELF_CHECK_BANNER)
    for disclaimer in metrics.disclaimers:
        print(disclaimer)
    print(_PERSONALIZATION_NOTE)
    print(_PERMANENT_DISCLAIMER)
    print(evaluation.calibration_meaning_note)
    print(evaluation.deferred_note)


def _population_estimator(settings: object, evaluation: object) -> str:
    from engagevr.schemas.personalization import PersonalizationConfiguration
    from engagevr.schemas.targets import TaskType

    assert isinstance(settings, PersonalizationConfiguration)
    task_type = getattr(evaluation, "task_type", None)
    return (
        settings.population_model_classification
        if task_type is TaskType.CLASSIFICATION
        else settings.population_model_regression
    )


def _print_aggregates(aggregates: object) -> None:
    from engagevr.schemas.experiments import AggregateMetric

    assert isinstance(aggregates, tuple)
    for aggregate in aggregates:
        assert isinstance(aggregate, AggregateMetric)
        if aggregate.mean is None:
            print(
                f"  {aggregate.name:<30} unavailable ({aggregate.unavailable_reason})"
            )
        else:
            print(
                f"  {aggregate.name:<30} {aggregate.mean:.4f} +/- "
                f"{aggregate.standard_deviation:.4f} "
                f"({aggregate.valid_fold_count}/{aggregate.total_fold_count} folds)"
            )
