"""Milestone 5 CLI: ``features-demo``, ``baseline-demo``, ``baseline-train``.

Kept in its own module so ``__main__`` stays a thin dispatcher and so the
modelling commands can be tested without importing the webcam, rPPG, or
WebSocket code paths.

``features-demo`` and ``baseline-demo`` operate on SYNTHETIC data only and
print a permanent disclaimer.  ``baseline-train --mode scientific``
refuses any dataset whose predictors or targets are synthetic, or whose
target provenance is unstated.

No command in this module prints a number that describes a person.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from engagevr.schemas.experiments import (
    SOFTWARE_SELF_CHECK_BANNER,
    EvaluationMode,
)
from engagevr.schemas.targets import TargetName, UnsupportedTargetError

#: Printed by every command in this module.
_PERMANENT_DISCLAIMER = (
    "EngageVR produces ESTIMATES from software measurements. Nothing here is "
    "a medical, diagnostic, psychological, or clinical conclusion, and no "
    "number printed by these commands is experimental evidence about any "
    "person."
)

_SYNTHETIC_BANNER = (
    "=== SYNTHETIC DATA ===\n"
    "Every row and every target below was generated by software from a known\n"
    "latent process. No person was recorded. No metric computed from this\n"
    "data is model accuracy, engagement validity, cognitive-load validity, or\n"
    "evidence of any kind, and none may be compared with a published result\n"
    "on real data."
)


def add_parsers(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Register the Milestone 5 subcommands on an existing subparser set."""
    features = sub.add_parser(
        "features-demo",
        help="Build a deterministic SYNTHETIC windowed-feature dataset.",
    )
    features.add_argument("--seed", type=int, default=42)
    features.add_argument("--subjects", type=int, default=30)
    features.add_argument("--sessions-per-subject", type=int, default=2)
    features.add_argument("--windows-per-session", type=int, default=20)
    features.add_argument("--window-seconds", type=float, default=None)
    features.add_argument("--step-seconds", type=float, default=None)
    features.add_argument(
        "--imbalanced",
        action="store_true",
        help="Shift the class thresholds to produce an imbalanced dataset.",
    )
    features.add_argument(
        "--output",
        type=str,
        default="artifacts/datasets/m5-synthetic.parquet",
    )

    demo = sub.add_parser(
        "baseline-demo",
        help="Run baseline software verification on a SYNTHETIC dataset.",
    )
    _add_training_arguments(demo)
    demo.add_argument(
        "--output",
        type=str,
        default="artifacts/experiments/m5-baseline-demo",
    )

    train = sub.add_parser(
        "baseline-train",
        help="Train and evaluate interpretable baselines on a dataset.",
    )
    _add_training_arguments(train)
    train.add_argument(
        "--mode",
        type=str,
        default="self-check",
        choices=["self-check", "scientific"],
        help="Scientific mode rejects synthetic predictors or targets.",
    )
    train.add_argument(
        "--output",
        type=str,
        default="artifacts/experiments/baseline-run",
    )


def _add_training_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dataset",
        type=str,
        default="artifacts/datasets/m5-synthetic.parquet",
    )
    parser.add_argument(
        "--target",
        type=str,
        default=TargetName.ENGAGEMENT_CLASS.value,
        choices=[t.value for t in TargetName],
    )
    parser.add_argument("--folds", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--models",
        type=str,
        default=None,
        help="Comma-separated model names. Default: every registered model.",
    )
    parser.add_argument(
        "--calibration",
        type=str,
        default="sigmoid",
        choices=["none", "sigmoid", "isotonic"],
    )
    parser.add_argument("--calibration-group-fraction", type=float, default=0.25)
    parser.add_argument("--calibration-bins", type=int, default=10)
    parser.add_argument("--permutation-repeats", type=int, default=5)
    parser.add_argument(
        "--no-ablations",
        action="store_true",
        help="Skip the feature-group ablation comparison.",
    )
    parser.add_argument(
        "--tune",
        action="store_true",
        help="Enable the bounded small-grid, group-aware inner search.",
    )


def run_features_demo(args: argparse.Namespace) -> int:
    """Build and persist a deterministic SYNTHETIC feature dataset."""
    from engagevr.config import load_config
    from engagevr.features.assembly import (
        DatasetAssemblyError,
        catalog_path,
        metadata_path,
        write_dataset,
    )
    from engagevr.features.catalog import FEATURE_CATALOG
    from engagevr.features.synthetic import (
        SyntheticDatasetConfig,
        generate_synthetic_dataset,
    )
    from engagevr.features.validation import (
        DatasetValidationError,
        assert_no_identity_columns,
        validate_feature_windows,
    )

    config = load_config()
    duration = (
        args.window_seconds
        if args.window_seconds is not None
        else config.features.window_duration_seconds
    )
    step = (
        args.step_seconds
        if args.step_seconds is not None
        else config.features.window_step_seconds
    )
    thresholds = (0.25, 0.45) if args.imbalanced else (0.40, 0.60)

    try:
        synthetic = SyntheticDatasetConfig(
            seed=args.seed,
            subjects=args.subjects,
            sessions_per_subject=args.sessions_per_subject,
            windows_per_session=args.windows_per_session,
            window_duration_seconds=duration,
            window_step_seconds=step,
            engagement_class_thresholds=thresholds,
            cognitive_load_class_thresholds=thresholds,
        )
    except ValueError as exc:
        print(f"Error: invalid generator configuration: {exc}", file=sys.stderr)
        return 2

    rows = generate_synthetic_dataset(synthetic)
    target_names = list(TargetName)

    try:
        report = validate_feature_windows(rows, FEATURE_CATALOG)
    except DatasetValidationError as exc:
        print(f"Error: generated dataset failed validation: {exc}", file=sys.stderr)
        return 1

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        metadata = write_dataset(
            rows,
            output,
            target_names=target_names,
            window_duration_seconds=synthetic.window_duration_seconds,
            window_step_seconds=synthetic.window_step_seconds,
            windows_overlap=synthetic.windows_overlap,
            creation_configuration=synthetic.model_dump(mode="json"),
            random_seed=synthetic.seed,
        )
    except DatasetAssemblyError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    try:
        assert_no_identity_columns(metadata.column_order)
    except DatasetValidationError as exc:  # pragma: no cover - schema forbids it
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(_SYNTHETIC_BANNER)
    print()
    print(f"Rows:                   {metadata.row_count}")
    print(f"Synthetic subjects:     {metadata.subject_count}")
    print(f"Sessions:               {metadata.session_count}")
    print(f"Features in catalog:    {metadata.feature_count}")
    print(f"Feature catalog:        {metadata.feature_catalog_version}")
    print(f"Window duration (s):    {metadata.window_duration_seconds}")
    print(f"Window step (s):        {metadata.window_step_seconds}")
    print(f"Windows overlap:        {metadata.windows_overlap}")
    print(f"Overall missing (%):    {metadata.overall_missing_pct:.2f}")
    print(f"Random seed:            {metadata.random_seed}")
    print(f"Data-source counts:     {metadata.data_source_counts}")
    print(f"Dataset fingerprint:    {metadata.dataset_fingerprint}")
    print(f"Scientific evaluation:  {metadata.scientific_evaluation_eligible}")
    print()
    print("Targets:")
    for summary in metadata.targets:
        detail = (
            summary.class_distribution
            if summary.class_distribution is not None
            else {
                "minimum": summary.value_minimum,
                "maximum": summary.value_maximum,
                "mean": summary.value_mean,
            }
        )
        print(
            f"  {summary.target_name:<22} {summary.task_type:<15} "
            f"labelled={summary.labelled_row_count:<6} "
            f"scientific_evaluation_permitted={summary.scientific_evaluation_permitted}"
        )
        print(f"    {detail}")
    print()
    print(f"Dataset:                {output}")
    print(f"Metadata:               {metadata_path(output)}")
    print(f"Feature catalog:        {catalog_path(output)}")
    print(f"Validation checks:      {', '.join(report.checks_passed)}")
    print()
    print("SYNTHETIC DATA. Permanently labelled. Excluded from scientific")
    print("evaluation. Not evidence, not validation, not a performance claim.")
    print(_PERMANENT_DISCLAIMER)
    return 0


def run_baseline_demo(args: argparse.Namespace) -> int:
    """Run the baseline pipeline as a software self-check."""
    return _run_training(args, mode=EvaluationMode.SOFTWARE_SELF_CHECK)


def run_baseline_train(args: argparse.Namespace) -> int:
    """Run the baseline pipeline in the requested evaluation mode."""
    mode = (
        EvaluationMode.SCIENTIFIC
        if getattr(args, "mode", "self-check") == "scientific"
        else EvaluationMode.SOFTWARE_SELF_CHECK
    )
    return _run_training(args, mode=mode)


def _run_training(args: argparse.Namespace, *, mode: EvaluationMode) -> int:
    from engagevr.features.assembly import DatasetAssemblyError
    from engagevr.features.validation import DatasetValidationError, LeakageError
    from engagevr.training.artifacts import ArtifactError
    from engagevr.training.calibration import CalibrationError, CalibrationMethod
    from engagevr.training.models import UnsupportedModelError
    from engagevr.training.preprocessing import PreprocessingError
    from engagevr.training.runner import (
        EvaluationError,
        RunConfiguration,
        ScientificModeError,
        run_baselines,
    )
    from engagevr.training.splits import GroupOverlapError, SplitConfigurationError

    dataset = Path(args.dataset)
    if not dataset.exists():
        print(
            f"Error: dataset {dataset} does not exist. Build one first with "
            "'features-demo', or pass --dataset.",
            file=sys.stderr,
        )
        return 2
    if args.folds < 2:
        print(
            f"Error: --folds must be at least 2; got {args.folds}. A single "
            "fold has no held-out portion.",
            file=sys.stderr,
        )
        return 2

    try:
        target = TargetName(args.target)
    except ValueError:
        supported = ", ".join(t.value for t in TargetName)
        print(
            f"Error: unsupported target {args.target!r}; supported: {supported}",
            file=sys.stderr,
        )
        return 2

    model_names = (
        tuple(name.strip() for name in args.models.split(",") if name.strip())
        if args.models
        else ()
    )
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)

    config = RunConfiguration(
        dataset_path=dataset,
        target_name=target,
        output_directory=output,
        evaluation_mode=mode,
        n_splits=args.folds,
        random_seed=args.seed,
        model_names=model_names,
        calibration_method=CalibrationMethod(args.calibration),
        calibration_group_fraction=args.calibration_group_fraction,
        calibration_bins=args.calibration_bins,
        permutation_repeats=args.permutation_repeats,
        run_ablations=not args.no_ablations,
        tune_hyperparameters=args.tune,
    )

    if mode is EvaluationMode.SOFTWARE_SELF_CHECK:
        print(SOFTWARE_SELF_CHECK_BANNER)
        print(_SYNTHETIC_BANNER)
        print()

    try:
        result = run_baselines(config)
    except ScientificModeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 3
    except (
        SplitConfigurationError,
        GroupOverlapError,
        LeakageError,
        UnsupportedModelError,
        UnsupportedTargetError,
        CalibrationError,
        PreprocessingError,
        DatasetValidationError,
        DatasetAssemblyError,
        ArtifactError,
        EvaluationError,
    ) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    _print_result(result, config)
    return 0


def _print_result(result: object, config: object) -> None:
    from engagevr.training.runner import RunConfiguration, RunResult

    assert isinstance(result, RunResult)
    assert isinstance(config, RunConfiguration)
    metrics = result.metrics
    counts = result.manifest.configuration

    print(f"Run id:                 {result.run_id}")
    print(f"Experiment directory:   {result.directory}")
    print(f"Dataset:                {config.dataset_path}")
    print(f"Dataset fingerprint:    {metrics.dataset_fingerprint}")
    print(f"Data-source counts:     {_data_source_counts(result)}")
    print(f"Target:                 {metrics.target_name}")
    print(f"Task type:              {metrics.task_type}")
    print(f"Group field:            {metrics.group_field}")
    print(f"Independent groups:     {metrics.group_count}")
    print(f"Folds:                  {metrics.fold_count}")
    print(f"Split strategy:         {result.splits.strategy.value}")
    print(f"  reason:               {result.splits.strategy_reason}")
    print(f"Split audit passed:     {result.splits.audit_passed}")
    print(f"Calibration method:     {result.manifest.calibration_method}")
    print(f"Random seed:            {counts.get('random_seed')}")
    print(f"Evaluation mode:        {metrics.evaluation_mode.value}")
    print(f"Scientific evaluation:  {metrics.scientific_evaluation_eligible}")
    print()
    print("Models evaluated:")
    for model in metrics.results:
        marker = (
            " [software-check baseline]" if model.is_software_check_baseline else ""
        )
        print(f"  {model.model_name} ({model.model_kind}){marker}")
        for aggregate in model.aggregate:
            if aggregate.mean is None:
                print(
                    f"    {aggregate.name:<38} unavailable "
                    f"({aggregate.unavailable_reason})"
                )
            else:
                print(
                    f"    {aggregate.name:<38} "
                    f"{aggregate.mean:.4f} +/- {aggregate.standard_deviation:.4f} "
                    f"({aggregate.valid_fold_count}/{aggregate.total_fold_count} folds)"
                )
        if model.failed_folds:
            for index, reason in sorted(model.failed_folds.items()):
                print(f"    fold {index} produced no metrics: {reason}")
    if result.ablations is not None:
        print()
        print("Feature-group ablations (identical folds, fold-local preprocessing):")
        for ablation in result.ablations.results:
            if not ablation.available:
                print(
                    f"  {ablation.ablation_name:<26} unavailable: "
                    f"{ablation.unavailable_reason}"
                )
                continue
            headline = next(iter(ablation.aggregate), None)
            value = (
                "unavailable"
                if headline is None or headline.mean is None
                else f"{headline.name}={headline.mean:.4f}"
            )
            print(
                f"  {ablation.ablation_name:<26} {len(ablation.feature_names):>3} "
                f"features  {value}"
            )
        print("  These are feature-subset comparisons only, NOT multimodal fusion.")
    if result.warnings:
        print()
        print("Warnings:")
        for warning in result.warnings:
            print(f"  {warning}")
    print()
    print(f"Metrics:                {result.directory / 'metrics.json'}")
    print(f"Splits:                 {result.directory / 'splits.json'}")
    print(f"Calibration:            {result.directory / 'calibration.json'}")
    print(f"Ablations:              {result.directory / 'ablations.json'}")
    print(f"Predictions:            {result.directory / 'predictions.parquet'}")
    print(f"Importances:            {result.directory / 'feature_importance.parquet'}")
    print(f"Manifest:               {result.directory / 'manifest.json'}")
    print()
    if metrics.evaluation_mode.value == "software_self_check":
        print(SOFTWARE_SELF_CHECK_BANNER)
    for disclaimer in metrics.disclaimers:
        print(disclaimer)
    print(_PERMANENT_DISCLAIMER)
    print(
        "No model here is a champion and none is production-ready; no model "
        "has been evaluated against real participant labels."
    )


def _data_source_counts(result: object) -> dict[str, int]:
    from engagevr.training.runner import RunResult

    assert isinstance(result, RunResult)
    path = Path(result.directory) / "dataset.json"
    if not path.exists():  # pragma: no cover - written before printing
        return {}
    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)
    counts = document.get("data_source_counts", {})
    return {str(key): int(value) for key, value in counts.items()}
