"""Deterministic SYNTHETIC windowed-feature generator for software verification.

Purpose
-------
This generator exists so that the modelling pipeline can be tested end to
end **without any participant data**.  Every row it produces is labelled
``SYNTHETIC`` permanently, every target it produces sets
``scientific_evaluation_permitted=False``, and no number computed from its
output is evidence about a person.

The hidden data-generating process
----------------------------------
Two latent variables drive each window and are **never emitted as
columns**:

- ``E`` — a latent "engagement" value in ``[0, 1]``;
- ``L`` — a latent "cognitive load" value in ``[0, 1]``.

They are built as::

    e_raw = e_base + subject_effect_e + session_effect_e + drift_e(t) + ar_e(t)
    l_raw = l_base + subject_effect_l + session_effect_l + drift_l(t)
            + ar_l(t) - coupling * (e_raw - e_base)
    E = clip(e_raw, 0, 1)
    L = clip(l_raw, 0, 1)

where ``subject_effect_*`` is one draw per synthetic subject (a **group
effect**), ``session_effect_*`` is one draw per session (a **session
effect**), ``drift_*`` is a linear trend across the session, ``ar_*`` is a
first-order autoregressive noise process across windows, and ``coupling``
makes load mildly anti-correlated with engagement.

Every observable feature is then drawn as::

    value = base + engagement_coefficient * (E - 0.5)
                 + load_coefficient * (L - 0.5)
                 + Normal(0, noise_sd)

clipped to the feature's catalog range.  A feature whose coefficients are
both zero is **irrelevant by construction** — it carries no information
about either latent — and several such features are included deliberately
so that feature selection and interpretation have something to get wrong.
A handful of features are additionally derived from others (for example,
the incorrect-response proportion is one minus the correct and timeout
proportions), which produces genuine collinearity.

Targets are noisy observations of the latents::

    engagement_score = clip(E + Normal(0, label_noise_sd), 0, 1)
    engagement_class = threshold(engagement_score, class_thresholds)

so a perfect score is not attainable even in principle.  The generator is
**not** tuned to make any model look good and is not tuned toward any
model family: the relationships are additive and monotone, which suits a
linear model, while the missingness, the clipping, and the class
thresholds introduce non-linearity, which suits a tree.  No choice here
was made after looking at a result.

What this is not
----------------
This is not a model of human behaviour, not a simulation of physiology,
and not a substitute for data.  It exercises code paths.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Self

import numpy as np
from pydantic import BaseModel, Field, model_validator

from engagevr.features.catalog import FEATURE_CATALOG, FEATURE_CATALOG_VERSION
from engagevr.features.windowing import window_id
from engagevr.schemas.features import (
    FEATURE_SCHEMA_VERSION,
    SYNTHETIC_LABEL,
    FeatureDtype,
    FeatureModality,
    FeatureWindow,
    SubjectKind,
    TargetValue,
)
from engagevr.schemas.session import DataSource, ExperimentCondition
from engagevr.schemas.targets import (
    COGNITIVE_LOAD_CLASSES,
    ENGAGEMENT_CLASSES,
    TargetName,
    TargetSourceType,
    TaskType,
)

#: Instrument recorded on every generated target.
SYNTHETIC_INSTRUMENT = "engagevr.features.synthetic:deterministic_generator"

#: Provenance note recorded on every generated target.
SYNTHETIC_PROVENANCE_NOTE = (
    "Generated by the EngageVR deterministic synthetic feature generator "
    "from a known latent process. No person, questionnaire, annotation, or "
    "measurement is involved. Scientific evaluation is prohibited."
)

#: Fixed epoch for generated sessions. A wall clock would make two builds
#: of the same seed differ, which would defeat the fingerprint.
_EPOCH = datetime(2026, 1, 1, 9, 0, 0, tzinfo=UTC)


@dataclass(frozen=True, slots=True)
class _FeatureRule:
    """How one observable feature is generated from the latent variables."""

    base: float
    engagement: float
    load: float
    noise: float
    minimum: float | None = None
    maximum: float | None = None
    integer: bool = False


#: The complete generation rule set. ``engagement`` and ``load`` are the
#: coefficients on ``(E - 0.5)`` and ``(L - 0.5)``. A rule with both set to
#: 0.0 generates a feature that is irrelevant by construction.
_RULES: dict[str, _FeatureRule] = {
    # --- behavioural -------------------------------------------------
    "face_presence_pct": _FeatureRule(92.0, 12.0, 0.0, 4.0, 0.0, 100.0),
    "eye_openness_proxy_mean": _FeatureRule(0.28, 0.06, -0.02, 0.02, 0.0, 0.6),
    "eye_openness_proxy_sd": _FeatureRule(0.04, -0.01, 0.01, 0.01, 0.0, 0.3),
    "eye_openness_proxy_min": _FeatureRule(0.18, 0.05, -0.02, 0.02, 0.0, 0.6),
    "blink_proxy_count": _FeatureRule(9.0, -2.0, 3.0, 2.0, 0.0, None, integer=True),
    "blink_proxy_rate_per_min": _FeatureRule(18.0, -4.0, 6.0, 3.0, 0.0, None),
    "eye_closure_mean_duration_s": _FeatureRule(0.18, -0.05, 0.04, 0.05, 0.0, None),
    "eye_closure_max_duration_s": _FeatureRule(0.45, -0.12, 0.10, 0.12, 0.0, None),
    "eye_closure_total_duration_s": _FeatureRule(1.6, -0.5, 0.5, 0.5, 0.0, None),
    # Irrelevant by construction: mouth geometry carries no latent signal.
    "mouth_opening_proxy_mean": _FeatureRule(0.12, 0.0, 0.0, 0.03, 0.0, 1.0),
    "mouth_opening_proxy_sd": _FeatureRule(0.03, 0.0, 0.0, 0.01, 0.0, 1.0),
    "mouth_opening_proxy_max": _FeatureRule(0.30, 0.0, 0.0, 0.08, 0.0, 1.0),
    "face_tracking_stable_pct": _FeatureRule(90.0, 6.0, 0.0, 5.0, 0.0, 100.0),
    "behavioural_missing_pct": _FeatureRule(4.0, 0.0, 0.0, 3.0, 0.0, 100.0),
    # --- head pose ---------------------------------------------------
    "head_yaw_mean_deg": _FeatureRule(0.0, -3.0, 0.0, 4.0, -90.0, 90.0),
    "head_yaw_sd_deg": _FeatureRule(4.0, -1.2, 0.8, 1.5, 0.0, None),
    "head_yaw_range_deg": _FeatureRule(14.0, -4.0, 3.0, 4.0, 0.0, None),
    # Irrelevant by construction.
    "head_pitch_mean_deg": _FeatureRule(-2.0, 0.0, 0.0, 4.0, -90.0, 90.0),
    "head_pitch_sd_deg": _FeatureRule(3.5, -1.0, 0.6, 1.2, 0.0, None),
    "head_pitch_range_deg": _FeatureRule(12.0, -3.0, 2.0, 3.5, 0.0, None),
    "head_roll_mean_deg": _FeatureRule(0.0, 0.0, 0.0, 3.0, -90.0, 90.0),
    "head_roll_sd_deg": _FeatureRule(2.5, 0.0, 0.0, 1.0, 0.0, None),
    "head_angular_velocity_mean_deg_s": _FeatureRule(6.0, -2.5, 1.5, 2.0, 0.0, None),
    "head_angular_velocity_max_deg_s": _FeatureRule(24.0, -8.0, 5.0, 6.0, 0.0, None),
    "head_motion_variability_deg_s": _FeatureRule(5.0, -1.8, 1.2, 1.8, 0.0, None),
    "head_pose_available_pct": _FeatureRule(90.0, 8.0, 0.0, 5.0, 0.0, 100.0),
    # --- rPPG --------------------------------------------------------
    "rppg_heart_rate_bpm": _FeatureRule(74.0, -3.0, 9.0, 4.0, 30.0, 200.0),
    "rppg_quality_score": _FeatureRule(0.62, 0.10, -0.06, 0.10, 0.0, 1.0),
    "rppg_roi_available_pct": _FeatureRule(88.0, 6.0, -3.0, 6.0, 0.0, 100.0),
    "rppg_valid_frame_pct": _FeatureRule(90.0, 5.0, -3.0, 5.0, 0.0, 100.0),
    "rppg_timestamp_jitter_s": _FeatureRule(0.008, 0.0, 0.0, 0.004, 0.0, None),
    "rppg_spectral_peak_ratio": _FeatureRule(0.45, 0.08, -0.05, 0.08, 0.0, 1.0),
    "rppg_peak_prominence": _FeatureRule(0.35, 0.06, -0.04, 0.08, 0.0, None),
    "rppg_illumination_stability": _FeatureRule(0.80, 0.0, 0.0, 0.10, 0.0, 1.0),
    "rppg_motion_score": _FeatureRule(12.0, -3.0, 2.0, 4.0, 0.0, None),
    "rppg_unavailable_window_pct": _FeatureRule(10.0, -6.0, 4.0, 6.0, 0.0, 100.0),
    # --- task --------------------------------------------------------
    "task_attempted_trials": _FeatureRule(8.0, 1.0, 0.0, 1.0, 0.0, None, integer=True),
    "task_completed_trials": _FeatureRule(8.0, 1.0, 0.0, 1.0, 0.0, None, integer=True),
    "task_correct_count": _FeatureRule(5.5, 2.0, -1.2, 1.0, 0.0, None, integer=True),
    "task_correct_proportion": _FeatureRule(0.70, 0.26, -0.16, 0.08, 0.0, 1.0),
    "task_incorrect_count": _FeatureRule(1.5, -0.8, 0.8, 0.8, 0.0, None, integer=True),
    "task_incorrect_proportion": _FeatureRule(0.18, -0.14, 0.10, 0.05, 0.0, 1.0),
    "task_timeout_count": _FeatureRule(0.8, -0.6, 0.5, 0.6, 0.0, None, integer=True),
    "task_timeout_proportion": _FeatureRule(0.12, -0.12, 0.06, 0.04, 0.0, 1.0),
    "task_reaction_time_mean_ms": _FeatureRule(520.0, -90.0, 120.0, 45.0, 80.0, None),
    "task_reaction_time_median_ms": _FeatureRule(505.0, -88.0, 118.0, 45.0, 80.0, None),
    "task_reaction_time_sd_ms": _FeatureRule(110.0, -20.0, 30.0, 20.0, 0.0, None),
    "task_reaction_time_min_ms": _FeatureRule(300.0, -50.0, 60.0, 30.0, 50.0, None),
    "task_reaction_time_max_ms": _FeatureRule(880.0, -140.0, 200.0, 70.0, 80.0, None),
    "task_difficulty_level": _FeatureRule(2.0, 0.0, 1.4, 0.6, 0.0, 5.0, integer=True),
    "task_pause_count": _FeatureRule(0.3, -0.3, 0.2, 0.4, 0.0, None, integer=True),
    "task_inactivity_seconds": _FeatureRule(1.2, -0.5, 0.4, 0.6, 0.0, None),
    # --- capture quality (irrelevant to the latents by construction) --
    "capture_brightness_mean": _FeatureRule(128.0, 0.0, 0.0, 18.0, 0.0, 255.0),
    "capture_blur_score_mean": _FeatureRule(160.0, 0.0, 0.0, 35.0, 0.0, None),
    "capture_motion_score_mean": _FeatureRule(14.0, -3.0, 2.0, 5.0, 0.0, None),
    "capture_underexposed_pct": _FeatureRule(3.0, 0.0, 0.0, 3.0, 0.0, 100.0),
    "capture_overexposed_pct": _FeatureRule(2.0, 0.0, 0.0, 2.0, 0.0, 100.0),
    "capture_blurry_pct": _FeatureRule(6.0, 0.0, 0.0, 5.0, 0.0, 100.0),
    "capture_dropped_frame_pct": _FeatureRule(1.5, 0.0, 0.0, 1.5, 0.0, 100.0),
    "window_missing_feature_pct": _FeatureRule(0.0, 0.0, 0.0, 0.0, 0.0, 100.0),
}

#: rPPG features that describe the pulse estimate itself. They are cleared
#: when the window's rPPG quality gate fails, because a rejected window
#: produced no pulse estimate to summarise.
_RPPG_ESTIMATE_FEATURES: tuple[str, ...] = (
    "rppg_heart_rate_bpm",
    "rppg_spectral_peak_ratio",
    "rppg_peak_prominence",
)


class SyntheticDatasetConfig(BaseModel):
    """Parameters of the synthetic data-generating process."""

    model_config = {"frozen": True, "extra": "forbid"}

    seed: int = 42
    subjects: int = Field(default=30, ge=2)
    sessions_per_subject: int = Field(default=2, ge=1)
    windows_per_session: int = Field(default=20, ge=2)

    window_duration_seconds: float = Field(default=10.0, gt=0.0)
    window_step_seconds: float = Field(default=10.0, gt=0.0)

    subject_effect_sd: float = Field(default=0.16, ge=0.0)
    session_effect_sd: float = Field(default=0.08, ge=0.0)
    drift_magnitude: float = Field(default=0.12, ge=0.0)
    autoregressive_coefficient: float = Field(default=0.55, ge=0.0, lt=1.0)
    process_noise_sd: float = Field(default=0.10, ge=0.0)
    engagement_load_coupling: float = Field(default=0.45, ge=0.0)
    label_noise_sd: float = Field(default=0.07, ge=0.0)

    engagement_class_thresholds: tuple[float, float] = (0.40, 0.60)
    cognitive_load_class_thresholds: tuple[float, float] = (0.40, 0.60)

    modality_dropout_probability: float = Field(default=0.10, ge=0.0, le=0.9)
    poor_quality_probability: float = Field(default=0.15, ge=0.0, le=0.9)
    rppg_quality_gate: float = Field(default=0.5, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _check(self) -> Self:
        if self.window_step_seconds > self.window_duration_seconds:
            raise ValueError(
                "window_step_seconds must not exceed window_duration_seconds"
            )
        for name, thresholds in (
            ("engagement_class_thresholds", self.engagement_class_thresholds),
            ("cognitive_load_class_thresholds", self.cognitive_load_class_thresholds),
        ):
            low, high = thresholds
            if not 0.0 < low < high < 1.0:
                raise ValueError(
                    f"{name} must satisfy 0 < low < high < 1; got {thresholds}"
                )
        return self

    @property
    def windows_overlap(self) -> bool:
        """Whether consecutive generated windows share evidence."""
        return self.window_step_seconds < self.window_duration_seconds


def subject_identifier(index: int) -> str:
    """Pseudonymous synthetic-subject identifier.

    Deliberately not "participant N": these are generated stand-ins and
    the identifier must never read as though a person were recorded.
    """
    return f"synthetic-subject-{index + 1:04d}"


def session_identifier(subject_index: int, session_index: int) -> str:
    """Deterministic synthetic-session identifier."""
    return f"synthetic-session-{subject_index + 1:04d}-{session_index + 1:02d}"


def _classify(
    value: float, thresholds: tuple[float, float], labels: tuple[str, ...]
) -> str:
    low, high = thresholds
    if value < low:
        return labels[0]
    if value < high:
        return labels[1]
    return labels[2]


def _target_value(
    *,
    target_name: TargetName,
    task_type: TaskType,
    class_value: str | None,
    numeric_value: float | None,
    subject_id: str,
    session_id: str,
    window_start: datetime,
    window_end: datetime,
) -> TargetValue:
    return TargetValue(
        target_name=target_name,
        task_type=task_type,
        class_value=class_value,
        numeric_value=numeric_value,
        source_type=TargetSourceType.SYNTHETIC_GENERATOR.value,
        source_instrument=SYNTHETIC_INSTRUMENT,
        observed_at_utc=window_end,
        interval_start_utc=window_start,
        interval_end_utc=window_end,
        synthetic_label=SYNTHETIC_LABEL,
        provenance_notes=(
            f"{SYNTHETIC_PROVENANCE_NOTE} Subject {subject_id}, session {session_id}."
        ),
        scientific_evaluation_permitted=False,
    )


def generate_synthetic_dataset(
    config: SyntheticDatasetConfig,
) -> tuple[FeatureWindow, ...]:
    """Generate a deterministic SYNTHETIC windowed-feature dataset.

    The same configuration always produces byte-identical rows, which is
    what makes the dataset fingerprint reproducible.

    Returns
    -------
    tuple[FeatureWindow, ...]
        Rows in generation order. Every row carries
        ``data_source=synthetic`` and ``synthetic_label='SYNTHETIC'``.
    """
    rng = np.random.default_rng(np.random.PCG64(config.seed))
    catalog = FEATURE_CATALOG
    numeric_names = tuple(
        e.canonical_name
        for e in catalog.entries
        if e.dtype is not FeatureDtype.CATEGORY
    )
    missing_rules = sorted(set(numeric_names) - set(_RULES))
    if missing_rules:  # pragma: no cover - guards a catalog/generator mismatch
        raise ValueError(
            f"the synthetic generator has no rule for catalog features: {missing_rules}"
        )

    rows: list[FeatureWindow] = []
    conditions = (
        ExperimentCondition.STATIC,
        ExperimentCondition.ADAPTIVE,
        ExperimentCondition.BASELINE,
    )

    for subject_index in range(config.subjects):
        subject_id = subject_identifier(subject_index)
        subject_effect_e = float(rng.normal(0.0, config.subject_effect_sd))
        subject_effect_l = float(rng.normal(0.0, config.subject_effect_sd))

        for session_index in range(config.sessions_per_subject):
            session_id = session_identifier(subject_index, session_index)
            session_effect_e = float(rng.normal(0.0, config.session_effect_sd))
            session_effect_l = float(rng.normal(0.0, config.session_effect_sd))
            drift_e = float(
                rng.uniform(-config.drift_magnitude, config.drift_magnitude)
            )
            drift_l = float(
                rng.uniform(-config.drift_magnitude, config.drift_magnitude)
            )
            condition = conditions[(subject_index + session_index) % len(conditions)]
            session_start = _EPOCH + timedelta(days=subject_index, hours=session_index)

            ar_e = 0.0
            ar_l = 0.0
            for window_index in range(config.windows_per_session):
                ar_e = config.autoregressive_coefficient * ar_e + float(
                    rng.normal(0.0, config.process_noise_sd)
                )
                ar_l = config.autoregressive_coefficient * ar_l + float(
                    rng.normal(0.0, config.process_noise_sd)
                )
                progress = (
                    window_index / (config.windows_per_session - 1)
                    if config.windows_per_session > 1
                    else 0.0
                )
                e_raw = (
                    0.5
                    + subject_effect_e
                    + session_effect_e
                    + drift_e * (progress - 0.5)
                    + ar_e
                )
                l_raw = (
                    0.5
                    + subject_effect_l
                    + session_effect_l
                    + drift_l * (progress - 0.5)
                    + ar_l
                    - config.engagement_load_coupling * (e_raw - 0.5)
                )
                latent_e = float(np.clip(e_raw, 0.0, 1.0))
                latent_l = float(np.clip(l_raw, 0.0, 1.0))

                rows.append(
                    _build_row(
                        rng=rng,
                        config=config,
                        subject_id=subject_id,
                        session_id=session_id,
                        condition=condition,
                        session_start=session_start,
                        window_index=window_index,
                        latent_e=latent_e,
                        latent_l=latent_l,
                    )
                )

    return tuple(rows)


def _build_row(
    *,
    rng: np.random.Generator,
    config: SyntheticDatasetConfig,
    subject_id: str,
    session_id: str,
    condition: ExperimentCondition,
    session_start: datetime,
    window_index: int,
    latent_e: float,
    latent_l: float,
) -> FeatureWindow:
    offset = window_index * config.window_step_seconds
    window_start = session_start + timedelta(seconds=offset)
    window_end = window_start + timedelta(seconds=config.window_duration_seconds)

    values: dict[str, float | None] = {}
    for name, rule in _RULES.items():
        raw = (
            rule.base
            + rule.engagement * (latent_e - 0.5)
            + rule.load * (latent_l - 0.5)
            + float(rng.normal(0.0, rule.noise))
        )
        if rule.minimum is not None:
            raw = max(raw, rule.minimum)
        if rule.maximum is not None:
            raw = min(raw, rule.maximum)
        values[name] = float(round(raw)) if rule.integer else float(raw)

    _apply_structural_relationships(values, config)

    categorical: dict[str, str | None] = {"rppg_method": "pos"}

    # Modality dropout and quality gating, applied after generation so the
    # underlying process is independent of what survived measurement.
    modality_available: dict[str, bool] = {}
    modality_quality: dict[str, float | None] = {}
    for modality in FEATURE_CATALOG.modalities():
        names = tuple(e.canonical_name for e in FEATURE_CATALOG.by_modality(modality))
        # Capture-quality diagnostics are never dropped: they are how a
        # missing modality is explained, so losing them would leave a hole
        # with no account of why it is there.
        dropped = (
            modality is not FeatureModality.QUALITY
            and float(rng.random()) < config.modality_dropout_probability
        )
        if dropped:
            for name in names:
                if name in values:
                    values[name] = None
                if name in categorical:
                    categorical[name] = None
            modality_available[modality.value] = False
            modality_quality[modality.value] = None
        else:
            modality_available[modality.value] = True
            modality_quality[modality.value] = _modality_quality(modality.value, values)

    if modality_available.get("rppg", False):
        quality = values.get("rppg_quality_score")
        poor = float(rng.random()) < config.poor_quality_probability
        if poor:
            quality = float(rng.uniform(0.0, config.rppg_quality_gate))
            values["rppg_quality_score"] = quality
            modality_quality["rppg"] = quality
        if quality is None or quality < config.rppg_quality_gate:
            # The gate failed: there is no accepted pulse estimate to
            # summarise. Diagnostics stay; the estimate does not.
            for name in _RPPG_ESTIMATE_FEATURES:
                values[name] = None
            values["rppg_unavailable_window_pct"] = 100.0

    available = {name: value is not None for name, value in values.items()}
    available.update({name: value is not None for name, value in categorical.items()})
    others = [n for n in available if n != "window_missing_feature_pct"]
    missing = sum(1 for n in others if not available[n])
    values["window_missing_feature_pct"] = 100.0 * missing / len(others)
    available["window_missing_feature_pct"] = True

    engagement_score = float(
        np.clip(latent_e + rng.normal(0.0, config.label_noise_sd), 0.0, 1.0)
    )
    load_score = float(
        np.clip(latent_l + rng.normal(0.0, config.label_noise_sd), 0.0, 1.0)
    )
    targets = {
        TargetName.ENGAGEMENT_SCORE.value: _target_value(
            target_name=TargetName.ENGAGEMENT_SCORE,
            task_type=TaskType.REGRESSION,
            class_value=None,
            numeric_value=engagement_score,
            subject_id=subject_id,
            session_id=session_id,
            window_start=window_start,
            window_end=window_end,
        ),
        TargetName.ENGAGEMENT_CLASS.value: _target_value(
            target_name=TargetName.ENGAGEMENT_CLASS,
            task_type=TaskType.CLASSIFICATION,
            class_value=_classify(
                engagement_score,
                config.engagement_class_thresholds,
                ENGAGEMENT_CLASSES,
            ),
            numeric_value=None,
            subject_id=subject_id,
            session_id=session_id,
            window_start=window_start,
            window_end=window_end,
        ),
        TargetName.COGNITIVE_LOAD_SCORE.value: _target_value(
            target_name=TargetName.COGNITIVE_LOAD_SCORE,
            task_type=TaskType.REGRESSION,
            class_value=None,
            numeric_value=load_score,
            subject_id=subject_id,
            session_id=session_id,
            window_start=window_start,
            window_end=window_end,
        ),
        TargetName.COGNITIVE_LOAD_CLASS.value: _target_value(
            target_name=TargetName.COGNITIVE_LOAD_CLASS,
            task_type=TaskType.CLASSIFICATION,
            class_value=_classify(
                load_score,
                config.cognitive_load_class_thresholds,
                COGNITIVE_LOAD_CLASSES,
            ),
            numeric_value=None,
            subject_id=subject_id,
            session_id=session_id,
            window_start=window_start,
            window_end=window_end,
        ),
    }

    return FeatureWindow(
        window_id=window_id(session_id, window_index),
        session_id=session_id,
        subject_id=subject_id,
        subject_kind=SubjectKind.SYNTHETIC_SUBJECT,
        experiment_condition=condition,
        data_source=DataSource.SYNTHETIC,
        synthetic_label=SYNTHETIC_LABEL,
        window_index=window_index,
        window_start_utc=window_start,
        window_end_utc=window_end,
        window_start_monotonic_seconds=offset,
        window_end_monotonic_seconds=offset + config.window_duration_seconds,
        window_duration_seconds=config.window_duration_seconds,
        window_step_seconds=config.window_step_seconds,
        windows_overlap=config.windows_overlap,
        features=values,
        categorical_features=categorical,
        feature_available=available,
        modality_available=modality_available,
        modality_quality=modality_quality,
        targets=targets,
        feature_schema_version=FEATURE_SCHEMA_VERSION,
        feature_catalog_version=FEATURE_CATALOG_VERSION,
    )


def _apply_structural_relationships(
    values: dict[str, float | None], config: SyntheticDatasetConfig
) -> None:
    """Impose the arithmetic relationships that real aggregation would.

    These produce genuine collinearity: the three response proportions sum
    to one, the minimum eye-openness never exceeds the mean, counts are
    consistent with their proportions, and the reaction-time order
    statistics are ordered. A generator that ignored these would produce a
    table no aggregation step could ever have emitted.
    """
    correct = _as_float(values["task_correct_proportion"])
    timeout = _as_float(values["task_timeout_proportion"])
    total = correct + timeout
    if total > 1.0:
        correct /= total
        timeout /= total
    values["task_correct_proportion"] = correct
    values["task_timeout_proportion"] = timeout
    values["task_incorrect_proportion"] = max(0.0, 1.0 - correct - timeout)

    attempted = max(1.0, _as_float(values["task_attempted_trials"]))
    values["task_attempted_trials"] = attempted
    values["task_completed_trials"] = min(
        attempted, _as_float(values["task_completed_trials"])
    )
    values["task_correct_count"] = float(round(attempted * correct))
    values["task_timeout_count"] = float(round(attempted * timeout))
    values["task_incorrect_count"] = max(
        0.0,
        attempted
        - _as_float(values["task_correct_count"])
        - _as_float(values["task_timeout_count"]),
    )

    mean_ear = _as_float(values["eye_openness_proxy_mean"])
    values["eye_openness_proxy_min"] = min(
        mean_ear, _as_float(values["eye_openness_proxy_min"])
    )

    rt_mean = _as_float(values["task_reaction_time_mean_ms"])
    values["task_reaction_time_min_ms"] = min(
        rt_mean, _as_float(values["task_reaction_time_min_ms"])
    )
    values["task_reaction_time_max_ms"] = max(
        rt_mean, _as_float(values["task_reaction_time_max_ms"])
    )
    values["task_reaction_time_median_ms"] = float(
        np.clip(
            _as_float(values["task_reaction_time_median_ms"]),
            _as_float(values["task_reaction_time_min_ms"]),
            _as_float(values["task_reaction_time_max_ms"]),
        )
    )

    duration_minutes = config.window_duration_seconds / 60.0
    rate = _as_float(values["blink_proxy_rate_per_min"])
    values["blink_proxy_count"] = float(round(rate * duration_minutes))

    yaw_sd = _as_float(values["head_yaw_sd_deg"])
    values["head_yaw_range_deg"] = max(
        _as_float(values["head_yaw_range_deg"]), 2.0 * yaw_sd
    )
    pitch_sd = _as_float(values["head_pitch_sd_deg"])
    values["head_pitch_range_deg"] = max(
        _as_float(values["head_pitch_range_deg"]), 2.0 * pitch_sd
    )


def _as_float(value: float | None) -> float:
    if value is None:  # pragma: no cover - structural step runs before dropout
        raise ValueError("structural relationships run before any value is cleared")
    return float(value)


def _modality_quality(modality: str, values: dict[str, float | None]) -> float | None:
    """Quality score reported for one modality of a generated window."""
    if modality == "rppg":
        return values.get("rppg_quality_score")
    if modality == "behavioural":
        presence = values.get("face_presence_pct")
        return None if presence is None else presence / 100.0
    if modality == "head_pose":
        pct = values.get("head_pose_available_pct")
        return None if pct is None else pct / 100.0
    if modality == "quality":
        blurry = values.get("capture_blurry_pct")
        return None if blurry is None else max(0.0, 1.0 - blurry / 100.0)
    return 1.0
