"""Windowed-feature dataset schemas, column conventions, and metadata.

A *feature window* is one row of the modelling dataset: a fixed-duration
slice of one session, summarised into named scalar features, each paired
with an explicit availability flag.

Design rules encoded here
-------------------------
- Feature values, availability flags, signal quality, targets, and
  provenance live in **separate columns with separate prefixes**.  They
  are never merged, because "0.0" and "we could not measure it" are
  different observations and collapsing them destroys the difference.
- A missing measurement is ``None``.  It is never zero-filled at this
  layer; imputation is a modelling decision made inside a training fold.
- Poor signal quality is recorded as quality, never as a feature value
  and never as a low target value.
- Nothing that could identify a person is representable: there is no
  column for a name, an email, a frame, an image, or a landmark array,
  and :mod:`engagevr.features.validation` asserts none appears.
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Self

from pydantic import BaseModel, Field, model_validator

from engagevr.schemas.session import DataSource, ExperimentCondition
from engagevr.schemas.targets import TARGET_DISCLAIMER, TargetName, TaskType

#: Version of the row schema (identity, time, and column conventions).
FEATURE_SCHEMA_VERSION = "1.0"

#: Permanent marker attached to every synthetic dataset row.
SYNTHETIC_LABEL = "SYNTHETIC"

#: Disclaimer persisted with every dataset built from synthetic input.
SYNTHETIC_DATASET_DISCLAIMER = (
    "SYNTHETIC DATASET. Every row was generated by software from a known "
    "data-generating process for the sole purpose of verifying that this "
    "pipeline is correct. No row describes a person. No metric computed "
    "from this dataset is experimental evidence, model accuracy, "
    "engagement validity, cognitive-load validity, or a performance claim, "
    "and none may be compared with a published result on real data."
)


# ---------------------------------------------------------------------------
# Column conventions
# ---------------------------------------------------------------------------

#: Measured or aggregated feature value. Nullable.
FEATURE_PREFIX = "feat__"
#: Per-feature availability flag. Never null.
AVAILABILITY_PREFIX = "avail__"
#: Whether a modality contributed anything to this window. Never null.
MODALITY_AVAILABLE_PREFIX = "modality_available__"
#: Modality signal quality in [0, 1]. Nullable when the modality is absent.
MODALITY_QUALITY_PREFIX = "modality_quality__"
#: Target value. Nullable: a dataset may carry no labels at all.
TARGET_PREFIX = "target__"
#: Target provenance field, ``target_meta__<target>__<field>``.
TARGET_META_PREFIX = "target_meta__"

#: Provenance fields carried per target, per row.
TARGET_META_FIELDS: tuple[str, ...] = (
    "task_type",
    "source_type",
    "source_instrument",
    "observed_at_utc",
    "interval_start_utc",
    "interval_end_utc",
    "synthetic_label",
    "provenance_notes",
    "scientific_evaluation_permitted",
)

#: Identity and grouping columns. Present on every row.
IDENTITY_COLUMNS: tuple[str, ...] = (
    "window_id",
    "session_id",
    "subject_id",
    "subject_kind",
    "experiment_condition",
    "data_source",
    "synthetic_label",
)

#: Window geometry and timing columns. Present on every row.
TIME_COLUMNS: tuple[str, ...] = (
    "window_index",
    "window_start_utc",
    "window_end_utc",
    "window_start_monotonic_seconds",
    "window_end_monotonic_seconds",
    "window_duration_seconds",
    "window_step_seconds",
    "windows_overlap",
)

#: Schema-version columns. Present on every row.
SCHEMA_COLUMNS: tuple[str, ...] = (
    "feature_schema_version",
    "feature_catalog_version",
)

#: Every column that is structurally forbidden from the predictor matrix.
#: Identifiers leak group membership, timestamps leak session ordering, and
#: target/provenance columns leak the answer.
NON_PREDICTOR_COLUMNS: frozenset[str] = frozenset(
    IDENTITY_COLUMNS + TIME_COLUMNS + SCHEMA_COLUMNS
)


def feature_column(name: str) -> str:
    """Column holding the value of feature ``name``."""
    return f"{FEATURE_PREFIX}{name}"


def availability_column(name: str) -> str:
    """Column holding the availability flag of feature ``name``."""
    return f"{AVAILABILITY_PREFIX}{name}"


def modality_available_column(modality: str) -> str:
    """Column holding whether ``modality`` contributed to a window."""
    return f"{MODALITY_AVAILABLE_PREFIX}{modality}"


def modality_quality_column(modality: str) -> str:
    """Column holding the quality score of ``modality``."""
    return f"{MODALITY_QUALITY_PREFIX}{modality}"


def target_column(target_name: TargetName | str) -> str:
    """Column holding the value of ``target_name``."""
    value = target_name.value if isinstance(target_name, TargetName) else target_name
    return f"{TARGET_PREFIX}{value}"


def target_meta_column(target_name: TargetName | str, field: str) -> str:
    """Column holding one provenance ``field`` of ``target_name``."""
    if field not in TARGET_META_FIELDS:
        raise ValueError(
            f"unknown target provenance field {field!r}; "
            f"known fields: {', '.join(TARGET_META_FIELDS)}"
        )
    value = target_name.value if isinstance(target_name, TargetName) else target_name
    return f"{TARGET_META_PREFIX}{value}__{field}"


def is_target_related_column(column: str) -> bool:
    """Whether ``column`` carries a target value or target provenance."""
    return column.startswith((TARGET_PREFIX, TARGET_META_PREFIX))


# ---------------------------------------------------------------------------
# Feature catalog
# ---------------------------------------------------------------------------


class FeatureModality(enum.StrEnum):
    """Feature groups used for ablation and for modality availability."""

    BEHAVIOURAL = "behavioural"
    HEAD_POSE = "head_pose"
    RPPG = "rppg"
    TASK = "task"
    QUALITY = "quality"


class FeatureDtype(enum.StrEnum):
    """Storage type of a feature column."""

    FLOAT = "float"
    INT = "int"
    BOOL = "bool"
    CATEGORY = "category"


class MissingBehaviour(enum.StrEnum):
    """What an absent measurement means for one feature.

    The distinction between ``NULL_WHEN_UNAVAILABLE`` and
    ``ZERO_WHEN_NO_EVENTS`` is the difference between "we could not look"
    and "we looked and there was nothing".  A blink count of 0 over a
    window in which a face was tracked throughout is a real observation;
    a blink count over a window with no face at all is not.
    """

    NULL_WHEN_UNAVAILABLE = "null_when_unavailable"
    NULL_WHEN_EVIDENCE_INSUFFICIENT = "null_when_evidence_insufficient"
    ZERO_WHEN_NO_EVENTS = "zero_when_no_events"


class FeatureSpec(BaseModel):
    """Catalog entry describing exactly one feature.

    A feature that has no entry here cannot appear in a dataset and cannot
    reach a model: :mod:`engagevr.training.preprocessing` rejects undeclared
    columns rather than passing them through.
    """

    model_config = {"frozen": True, "extra": "forbid"}

    canonical_name: str = Field(min_length=1)
    description: str = Field(min_length=1)
    modality: FeatureModality
    unit: str = Field(
        min_length=1,
        description="Physical or counting unit, or 'dimensionless'.",
    )
    aggregation_formula: str = Field(
        min_length=1,
        description="How the window value is computed from within-window evidence.",
    )
    minimum_evidence: str = Field(
        min_length=1,
        description="Evidence required before the value is computed at all.",
    )
    missing_behaviour: MissingBehaviour
    quality_dependency: str = Field(
        min_length=1,
        description="Which quality gate, if any, must pass first.",
    )
    permitted_predictor: bool = Field(
        description="Whether this feature may be used as a model input."
    )
    dtype: FeatureDtype = FeatureDtype.FLOAT
    value_minimum: float | None = None
    value_maximum: float | None = None

    @model_validator(mode="after")
    def _check(self) -> Self:
        if (
            self.value_minimum is not None
            and self.value_maximum is not None
            and self.value_minimum > self.value_maximum
        ):
            raise ValueError(
                f"feature {self.canonical_name!r}: value_minimum exceeds value_maximum"
            )
        if self.dtype is FeatureDtype.CATEGORY and self.permitted_predictor:
            raise ValueError(
                f"feature {self.canonical_name!r}: categorical features are not "
                "permitted predictors in this milestone"
            )
        return self


class FeatureCatalog(BaseModel):
    """An ordered, versioned collection of :class:`FeatureSpec` entries.

    Order is part of the contract.  It fixes column order in the dataset,
    which in turn is part of the dataset fingerprint, so a reordering is a
    detectable change rather than a silent one.
    """

    model_config = {"frozen": True}

    version: str = Field(min_length=1)
    entries: tuple[FeatureSpec, ...]

    @model_validator(mode="after")
    def _check(self) -> Self:
        names = [entry.canonical_name for entry in self.entries]
        duplicates = sorted({n for n in names if names.count(n) > 1})
        if duplicates:
            raise ValueError(f"duplicate feature names in catalog: {duplicates}")
        return self

    def names(self) -> tuple[str, ...]:
        """Canonical names, in catalog order."""
        return tuple(entry.canonical_name for entry in self.entries)

    def get(self, name: str) -> FeatureSpec:
        """Return the entry named ``name``.

        Raises
        ------
        KeyError
            If the feature is not in the catalog.
        """
        for entry in self.entries:
            if entry.canonical_name == name:
                return entry
        raise KeyError(f"feature {name!r} is not in feature catalog {self.version}")

    def by_modality(self, modality: FeatureModality) -> tuple[FeatureSpec, ...]:
        """Entries belonging to ``modality``, in catalog order."""
        return tuple(e for e in self.entries if e.modality is modality)

    def predictor_names(self) -> tuple[str, ...]:
        """Names of features permitted as model inputs, in catalog order."""
        return tuple(e.canonical_name for e in self.entries if e.permitted_predictor)

    def modalities(self) -> tuple[FeatureModality, ...]:
        """Modalities present in the catalog, in declaration order."""
        seen: list[FeatureModality] = []
        for entry in self.entries:
            if entry.modality not in seen:
                seen.append(entry.modality)
        return tuple(seen)


# ---------------------------------------------------------------------------
# Rows
# ---------------------------------------------------------------------------


class SubjectKind(enum.StrEnum):
    """Whether a row's subject is a real person or a generated stand-in."""

    PARTICIPANT = "participant"
    SYNTHETIC_SUBJECT = "synthetic_subject"


class TargetValue(BaseModel):
    """A target value plus the provenance that travels with it on the row."""

    model_config = {"extra": "forbid"}

    target_name: TargetName
    task_type: TaskType
    class_value: str | None = None
    numeric_value: float | None = None

    source_type: str = Field(min_length=1)
    source_instrument: str = Field(min_length=1)
    observed_at_utc: datetime
    interval_start_utc: datetime
    interval_end_utc: datetime
    synthetic_label: str | None = None
    provenance_notes: str = Field(min_length=1)
    scientific_evaluation_permitted: bool


class FeatureWindow(BaseModel):
    """One row of the windowed feature dataset.

    ``features`` and ``feature_available`` share the same key set: every
    catalog feature appears in both, so "absent from the dict" can never be
    confused with "measured as null".
    """

    model_config = {"extra": "forbid"}

    window_id: str = Field(min_length=1)
    session_id: str = Field(min_length=1)
    subject_id: str = Field(
        min_length=1,
        description="Pseudonymous subject identifier. Never a name or an email.",
    )
    subject_kind: SubjectKind
    experiment_condition: ExperimentCondition
    data_source: DataSource
    synthetic_label: str | None = None

    window_index: int = Field(ge=0)
    window_start_utc: datetime
    window_end_utc: datetime
    window_start_monotonic_seconds: float | None = None
    window_end_monotonic_seconds: float | None = None
    window_duration_seconds: float = Field(gt=0.0)
    window_step_seconds: float = Field(gt=0.0)
    windows_overlap: bool

    features: dict[str, float | None]
    categorical_features: dict[str, str | None] = Field(default_factory=dict)
    feature_available: dict[str, bool]
    modality_available: dict[str, bool]
    modality_quality: dict[str, float | None]
    targets: dict[str, TargetValue] = Field(default_factory=dict)

    feature_schema_version: str = FEATURE_SCHEMA_VERSION
    feature_catalog_version: str

    @model_validator(mode="after")
    def _check(self) -> Self:
        if self.window_end_utc <= self.window_start_utc:
            raise ValueError(
                f"window {self.window_id!r}: window_end_utc must be strictly "
                "after window_start_utc"
            )
        start = self.window_start_monotonic_seconds
        end = self.window_end_monotonic_seconds
        if (start is None) != (end is None):
            raise ValueError(
                f"window {self.window_id!r}: monotonic bounds must be supplied "
                "together or not at all"
            )
        if start is not None and end is not None and end <= start:
            raise ValueError(
                f"window {self.window_id!r}: monotonic end must be strictly "
                "after monotonic start"
            )
        shared = set(self.features) & set(self.categorical_features)
        if shared:
            raise ValueError(
                f"window {self.window_id!r}: features declared both numeric and "
                f"categorical: {sorted(shared)}"
            )
        declared = set(self.features) | set(self.categorical_features)
        missing_flags = declared - set(self.feature_available)
        if missing_flags:
            raise ValueError(
                f"window {self.window_id!r}: features without an availability "
                f"flag: {sorted(missing_flags)}"
            )
        extra_flags = set(self.feature_available) - declared
        if extra_flags:
            raise ValueError(
                f"window {self.window_id!r}: availability flags without a "
                f"feature: {sorted(extra_flags)}"
            )
        values: dict[str, object | None] = dict(self.features)
        values.update(self.categorical_features)
        for name, value in values.items():
            if value is None:
                if self.feature_available[name]:
                    raise ValueError(
                        f"window {self.window_id!r}: feature {name!r} is null but "
                        "marked available"
                    )
            elif not self.feature_available[name]:
                raise ValueError(
                    f"window {self.window_id!r}: feature {name!r} has a value but "
                    "is marked unavailable"
                )
        if self.data_source is DataSource.SYNTHETIC:
            if self.synthetic_label != SYNTHETIC_LABEL:
                raise ValueError(
                    f"window {self.window_id!r}: a synthetic row must carry "
                    f"synthetic_label={SYNTHETIC_LABEL!r}"
                )
            if self.subject_kind is not SubjectKind.SYNTHETIC_SUBJECT:
                raise ValueError(
                    f"window {self.window_id!r}: a synthetic row must have "
                    "subject_kind=synthetic_subject"
                )
        elif self.synthetic_label is not None:
            raise ValueError(
                f"window {self.window_id!r}: a non-synthetic row must leave "
                "synthetic_label unset"
            )
        return self


# ---------------------------------------------------------------------------
# Dataset metadata
# ---------------------------------------------------------------------------


class MissingnessSummary(BaseModel):
    """Per-feature missingness across a dataset."""

    model_config = {"frozen": True}

    feature_name: str
    missing_count: int = Field(ge=0)
    missing_pct: float = Field(ge=0.0, le=100.0)


class TargetSummary(BaseModel):
    """Class distribution or numeric summary for one target in a dataset."""

    model_config = {"frozen": True}

    target_name: str
    task_type: str
    labelled_row_count: int = Field(ge=0)
    class_distribution: dict[str, int] | None = None
    value_minimum: float | None = None
    value_maximum: float | None = None
    value_mean: float | None = None
    source_types: dict[str, int] = Field(default_factory=dict)
    scientific_evaluation_permitted: bool = False


class DatasetMetadata(BaseModel):
    """Deterministic provenance document written beside every dataset.

    ``created_at_utc`` is deliberately **excluded** from the canonical
    content used to compute ``dataset_fingerprint``: two equivalent builds
    of the same data must fingerprint identically, and a wall clock would
    make that impossible.
    """

    model_config = {"extra": "forbid"}

    dataset_schema_version: str = FEATURE_SCHEMA_VERSION
    feature_catalog_version: str

    row_count: int = Field(ge=0)
    feature_count: int = Field(ge=0)
    column_order: tuple[str, ...]

    subject_count: int = Field(ge=0)
    session_count: int = Field(ge=0)
    data_source_counts: dict[str, int]
    subject_kind_counts: dict[str, int]
    experiment_condition_counts: dict[str, int]

    window_duration_seconds: float = Field(gt=0.0)
    window_step_seconds: float = Field(gt=0.0)
    windows_overlap: bool

    missingness: tuple[MissingnessSummary, ...] = ()
    overall_missing_pct: float = Field(default=0.0, ge=0.0, le=100.0)
    targets: tuple[TargetSummary, ...] = ()

    creation_configuration: dict[str, object] = Field(default_factory=dict)
    random_seed: int | None = Field(
        default=None, description="Set only for generated datasets."
    )
    input_session_fingerprints: dict[str, str] = Field(default_factory=dict)

    dataset_fingerprint: str = Field(
        min_length=64,
        max_length=64,
        description="SHA-256 over canonical row content, column order, and schema.",
    )
    fingerprint_algorithm: str = "sha256"
    fingerprint_inputs: str = (
        "column order, schema versions, feature catalog version, window "
        "geometry, and every row's canonical value list. Excludes "
        "created_at_utc and any other wall-clock value."
    )

    created_at_utc: datetime
    scientific_evaluation_eligible: bool
    disclaimers: tuple[str, ...] = (TARGET_DISCLAIMER,)
