"""Target (label) schemas and target provenance.

Scope note
----------
**No validated EngageVR participant labels exist.**  This module defines
the *shape* a real engagement or cognitive-load label would have to take,
together with the provenance that would have to accompany it.  It does
not create such labels, and nothing in this repository has produced one.

Three separations are enforced here rather than left to convention:

1. A **target value** is separate from its **provenance**.  A value with
   no stated source instrument is rejected, because a number whose origin
   is unknown cannot be evaluated against.
2. A **synthetic** target is permanently labelled and is never permitted
   for scientific evaluation.  ``scientific_evaluation_permitted`` is
   forced to ``False`` for synthetic sources; it cannot be overridden.
3. A **measurement** is never silently promoted to a **label**.  Task
   accuracy, reaction time, difficulty level, and physiological estimates
   are predictors or outcome measurements.  Converting one into an
   engagement or cognitive-load label is a research claim, not a data
   transformation, and :func:`reject_automatic_derivation` refuses it.
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Self

from pydantic import BaseModel, Field, model_validator

from engagevr.schemas.session import DataSource

#: Permanent marker attached to every synthetic target observation.
SYNTHETIC_LABEL = "SYNTHETIC"

#: Disclaimer persisted alongside every target document.
TARGET_DISCLAIMER = (
    "Engagement and cognitive load are latent constructs. A target value "
    "in this repository is either SYNTHETIC (generated by software for "
    "pipeline verification) or absent. No validated participant label, "
    "questionnaire score, or expert annotation exists in this project, and "
    "no target here constitutes psychological, clinical, or diagnostic "
    "evidence."
)


class TargetName(enum.StrEnum):
    """Targets the modelling pipeline knows how to evaluate."""

    ENGAGEMENT_CLASS = "engagement_class"
    ENGAGEMENT_SCORE = "engagement_score"
    COGNITIVE_LOAD_CLASS = "cognitive_load_class"
    COGNITIVE_LOAD_SCORE = "cognitive_load_score"


class TaskType(enum.StrEnum):
    """Supervised learning task implied by a target."""

    CLASSIFICATION = "classification"
    REGRESSION = "regression"


class TargetSourceType(enum.StrEnum):
    """Where a target value came from.

    ``SYNTHETIC_GENERATOR`` is the only member this repository can
    currently produce.  The others are declared so that real labels can be
    ingested later without redefining the schema, and so that a reader can
    see at a glance which categories remain empty.
    """

    SUBJECTIVE_SELF_REPORT = "subjective_self_report"
    EXPERIMENT_CONDITION = "experiment_condition"
    EXPERT_ANNOTATION = "expert_annotation"
    PUBLIC_DATASET_ANNOTATION = "public_dataset_annotation"
    SYNTHETIC_GENERATOR = "synthetic_generator"


#: Source categories that can never support scientific evaluation.
NON_SCIENTIFIC_SOURCE_TYPES: frozenset[TargetSourceType] = frozenset(
    {TargetSourceType.SYNTHETIC_GENERATOR}
)

#: Ordered class vocabularies. Order is part of the contract: it fixes the
#: column order of every confusion matrix and probability array, so a
#: stored result can be re-read without guessing which column is which.
ENGAGEMENT_CLASSES: tuple[str, ...] = ("low", "medium", "high")
COGNITIVE_LOAD_CLASSES: tuple[str, ...] = ("low", "medium", "high")


class TargetSpec(BaseModel):
    """Static definition of one target: its task type and value domain."""

    model_config = {"frozen": True}

    target_name: TargetName
    task_type: TaskType
    description: str

    class_vocabulary: tuple[str, ...] | None = Field(
        default=None,
        description="Ordered class labels. Required for classification.",
    )
    class_order_is_ordinal: bool = Field(
        default=False,
        description=(
            "Whether ``class_vocabulary`` declares an ORDERED scale, so that "
            "earlier entries are genuinely 'less' than later ones. Consumers "
            "that need an ordering must require this flag rather than reading "
            "one out of array position or alphabetical order: a nominal "
            "vocabulary listed in some arbitrary order would otherwise acquire "
            "an ordinal meaning it never had."
        ),
    )
    value_minimum: float | None = Field(
        default=None, description="Inclusive lower bound. Required for regression."
    )
    value_maximum: float | None = Field(
        default=None, description="Inclusive upper bound. Required for regression."
    )
    unit: str = Field(
        default="dimensionless",
        description="Unit of a regression target, or 'class' for classification.",
    )

    @model_validator(mode="after")
    def _check(self) -> Self:
        if self.task_type is TaskType.CLASSIFICATION:
            if not self.class_vocabulary:
                raise ValueError(
                    f"target {self.target_name.value!r} is a classification target "
                    "and must declare a class_vocabulary"
                )
            if self.class_order_is_ordinal and len(self.class_vocabulary) < 2:
                raise ValueError(
                    "a single-class vocabulary declares no order to be ordinal about"
                )
            if len(set(self.class_vocabulary)) != len(self.class_vocabulary):
                raise ValueError("class_vocabulary must not contain duplicates")
            if self.value_minimum is not None or self.value_maximum is not None:
                raise ValueError(
                    "a classification target must not declare a numeric range"
                )
        else:
            if self.class_vocabulary is not None:
                raise ValueError(
                    "a regression target must not declare a class_vocabulary"
                )
            if self.class_order_is_ordinal:
                raise ValueError("a regression target has no class vocabulary to order")
            if self.value_minimum is None or self.value_maximum is None:
                raise ValueError(
                    f"target {self.target_name.value!r} is a regression target and "
                    "must declare value_minimum and value_maximum"
                )
            if self.value_minimum >= self.value_maximum:
                raise ValueError("value_minimum must be strictly below value_maximum")
        return self


#: The four targets the Milestone 5 pipeline supports.
TARGET_SPECS: dict[TargetName, TargetSpec] = {
    TargetName.ENGAGEMENT_CLASS: TargetSpec(
        target_name=TargetName.ENGAGEMENT_CLASS,
        task_type=TaskType.CLASSIFICATION,
        description=(
            "Ordered engagement category for one window. Requires an external "
            "label source; this repository has none."
        ),
        class_vocabulary=ENGAGEMENT_CLASSES,
        class_order_is_ordinal=True,
        unit="class",
    ),
    TargetName.ENGAGEMENT_SCORE: TargetSpec(
        target_name=TargetName.ENGAGEMENT_SCORE,
        task_type=TaskType.REGRESSION,
        description=(
            "Continuous engagement score for one window, normalised to [0, 1]. "
            "Requires an external label source; this repository has none."
        ),
        value_minimum=0.0,
        value_maximum=1.0,
    ),
    TargetName.COGNITIVE_LOAD_CLASS: TargetSpec(
        target_name=TargetName.COGNITIVE_LOAD_CLASS,
        task_type=TaskType.CLASSIFICATION,
        description=(
            "Ordered cognitive-load category for one window. Requires an "
            "external label source; this repository has none."
        ),
        class_vocabulary=COGNITIVE_LOAD_CLASSES,
        class_order_is_ordinal=True,
        unit="class",
    ),
    TargetName.COGNITIVE_LOAD_SCORE: TargetSpec(
        target_name=TargetName.COGNITIVE_LOAD_SCORE,
        task_type=TaskType.REGRESSION,
        description=(
            "Continuous cognitive-load score for one window, normalised to "
            "[0, 1]. Requires an external label source; this repository has none."
        ),
        value_minimum=0.0,
        value_maximum=1.0,
    ),
}


def get_target_spec(target_name: TargetName | str) -> TargetSpec:
    """Return the :class:`TargetSpec` for ``target_name``.

    Raises
    ------
    UnsupportedTargetError
        If the name is not one of the supported targets.
    """
    try:
        key = TargetName(target_name)
    except ValueError as exc:
        supported = ", ".join(sorted(t.value for t in TargetName))
        raise UnsupportedTargetError(
            f"unsupported target {target_name!r}; supported targets: {supported}"
        ) from exc
    return TARGET_SPECS[key]


class UnsupportedTargetError(ValueError):
    """A requested target is not implemented by this pipeline."""


class TargetProvenanceError(ValueError):
    """A target was constructed without defensible provenance."""


class TargetObservation(BaseModel):
    """One labelled observation attached to one feature window.

    Every field required to judge whether the label may be used at all is
    carried on the observation itself, so provenance cannot be lost by
    moving the value into a table.
    """

    model_config = {"extra": "forbid"}

    target_name: TargetName
    task_type: TaskType

    class_value: str | None = Field(
        default=None, description="Class label. Set for classification only."
    )
    numeric_value: float | None = Field(
        default=None, description="Numeric value. Set for regression only."
    )

    class_vocabulary: tuple[str, ...] | None = None
    value_minimum: float | None = None
    value_maximum: float | None = None

    source_type: TargetSourceType
    source_instrument: str = Field(
        min_length=1,
        description=(
            "The instrument, questionnaire, annotation protocol, or generator "
            "that produced this value. Must be stated; an unattributed label "
            "cannot be evaluated against."
        ),
    )

    observed_at_utc: datetime = Field(
        description="UTC instant the label was recorded or generated."
    )
    interval_start_utc: datetime = Field(
        description="Start of the interval this label describes."
    )
    interval_end_utc: datetime = Field(
        description="End of the interval this label describes."
    )

    subject_id: str = Field(
        min_length=1, description="Pseudonymous subject identifier. Never a name."
    )
    session_id: str = Field(min_length=1)
    data_source: DataSource
    synthetic_label: str | None = Field(
        default=None,
        description="Permanently 'SYNTHETIC' for generated labels, else None.",
    )

    provenance_notes: str = Field(
        min_length=1,
        description="How this value came to exist, in plain language.",
    )
    scientific_evaluation_permitted: bool = Field(
        description=(
            "Whether this observation may enter a scientific evaluation. "
            "Forced to False for synthetic sources."
        )
    )

    @model_validator(mode="after")
    def _check(self) -> Self:
        spec = TARGET_SPECS[self.target_name]
        if self.task_type is not spec.task_type:
            raise ValueError(
                f"target {self.target_name.value!r} is a {spec.task_type.value} "
                f"target; got task_type={self.task_type.value!r}"
            )

        if self.task_type is TaskType.CLASSIFICATION:
            if self.numeric_value is not None:
                raise ValueError(
                    "a classification observation must not carry numeric_value"
                )
            if self.class_value is None:
                raise ValueError("a classification observation requires class_value")
            vocabulary = self.class_vocabulary or spec.class_vocabulary or ()
            if self.class_value not in vocabulary:
                raise ValueError(
                    f"class_value {self.class_value!r} is not in the vocabulary "
                    f"{list(vocabulary)} declared for "
                    f"{self.target_name.value!r}"
                )
        else:
            if self.class_value is not None:
                raise ValueError("a regression observation must not carry class_value")
            if self.numeric_value is None:
                raise ValueError("a regression observation requires numeric_value")
            low = self.value_minimum if self.value_minimum is not None else 0.0
            high = self.value_maximum if self.value_maximum is not None else 0.0
            if self.value_minimum is None:
                low = spec.value_minimum if spec.value_minimum is not None else 0.0
            if self.value_maximum is None:
                high = spec.value_maximum if spec.value_maximum is not None else 1.0
            if not low <= self.numeric_value <= high:
                raise ValueError(
                    f"numeric_value {self.numeric_value} is outside the declared "
                    f"range [{low}, {high}] for {self.target_name.value!r}"
                )

        if self.interval_end_utc < self.interval_start_utc:
            raise ValueError("interval_end_utc must not precede interval_start_utc")

        is_synthetic = (
            self.source_type in NON_SCIENTIFIC_SOURCE_TYPES
            or self.data_source is DataSource.SYNTHETIC
        )
        if is_synthetic:
            if self.synthetic_label != SYNTHETIC_LABEL:
                raise ValueError(
                    "a synthetic target observation must carry "
                    f"synthetic_label={SYNTHETIC_LABEL!r}"
                )
            if self.scientific_evaluation_permitted:
                raise ValueError(
                    "a synthetic target observation can never set "
                    "scientific_evaluation_permitted=True"
                )
        elif self.synthetic_label is not None:
            raise ValueError(
                "a non-synthetic target observation must leave synthetic_label unset"
            )
        return self


# ---------------------------------------------------------------------------
# Measurement-to-label guard
# ---------------------------------------------------------------------------

#: Measurements that are routinely — and wrongly — treated as if they were
#: engagement or cognitive-load ground truth.  Each entry names the reason
#: the conversion is refused, so the error message teaches rather than
#: merely blocking.
FORBIDDEN_AUTOMATIC_DERIVATIONS: dict[str, str] = {
    "task": (
        "task accuracy, error rate, timeout rate, and reaction time are "
        "software measurements of what the task program observed. A person "
        "can respond accurately while disengaged and slowly while highly "
        "engaged. They are predictors or outcome measurements, never an "
        "automatic engagement or cognitive-load label"
    ),
    "task_difficulty": (
        "difficulty level is an experimental manipulation, not a measurement "
        "of the load a particular person experienced. Treating it as "
        "cognitive load assumes the manipulation worked, which is the "
        "hypothesis, not the data"
    ),
    "rppg": (
        "heart rate from camera data is an unvalidated signal-processing "
        "estimate. Heart rate is not engagement and is not cognitive load; "
        "it responds to posture, temperature, movement, and illumination"
    ),
    "behavioural": (
        "blink proxies, eye-openness proxies, and head motion are observable "
        "behavioural proxies. Mapping them onto a psychological construct "
        "requires a validated instrument, which this project does not have"
    ),
    "head_pose": (
        "head orientation is a geometric estimate. Facing a screen is not "
        "attending to it, and looking away is not disengagement"
    ),
    "quality": (
        "signal quality describes the measurement, not the person. Poor "
        "quality must never be rendered as low engagement or high load"
    ),
}


def reject_automatic_derivation(
    *,
    source_group: str,
    target_name: TargetName | str,
) -> None:
    """Refuse to derive ``target_name`` automatically from ``source_group``.

    Called wherever a caller might be tempted to synthesise a label out of
    an available measurement.  There is no ``allow`` flag: producing a real
    label requires an external instrument and a documented protocol, not a
    keyword argument.

    Raises
    ------
    TargetProvenanceError
        Always, when ``source_group`` is a known measurement group.
    """
    reason = FORBIDDEN_AUTOMATIC_DERIVATIONS.get(source_group)
    name = (
        target_name.value if isinstance(target_name, TargetName) else str(target_name)
    )
    if reason is None:
        raise TargetProvenanceError(
            f"cannot derive target {name!r} from {source_group!r}: no documented "
            "label instrument exists for this project"
        )
    raise TargetProvenanceError(
        f"refusing to derive target {name!r} from the {source_group!r} feature "
        f"group: {reason}"
    )
