"""Dataset, quality, baseline, fusion, and personalization views.

Most of these tests are about wording, because on this dashboard the
wording is the safeguard.  A confusion matrix labelled *ground truth*, a
personalization delta labelled *improvement*, or a quality chart labelled
*engagement* would each be a scientific claim this repository cannot
support, and none of them would raise an exception on its own.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from engagevr.dashboard.views_dataset import (
    load_dataset_provenance,
    load_signal_quality,
)
from engagevr.dashboard.views_fusion import load_fusion, load_personalization
from engagevr.dashboard.views_models import (
    SYNTHETIC_ROW_AXIS,
    load_classification,
    load_regression,
    row_axis_label,
)
from engagevr.schemas.dashboard import UNAVAILABLE_TEXT
from tests.unit import dashboard_fixtures as fx


def cells(table: object) -> str:
    """Every cell, caption, and title of a table as one lowercase string."""
    assert table is not None
    parts = [table.title, table.caption or ""]  # type: ignore[attr-defined]
    parts.extend(table.columns)  # type: ignore[attr-defined]
    for row in table.rows:  # type: ignore[attr-defined]
        parts.extend(row)
    return " ".join(parts).lower()


def row_text(table: object) -> str:
    """Only the data cells, headings, and title -- never the caption.

    Several captions deny a reading in the reading's own words ("not an
    improvement", "does not rank subjects"). A banned-word check over the
    whole table would trip on the denial, so the wording checks look at
    the data the reader actually reads as a result, and the denial is
    asserted separately.
    """
    assert table is not None
    parts = [table.title]  # type: ignore[attr-defined]
    parts.extend(table.columns)  # type: ignore[attr-defined]
    for row in table.rows:  # type: ignore[attr-defined]
        parts.extend(row)
    return " ".join(parts).lower()


class TestDatasetProvenance:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_baseline_run(tmp_path)
        return load_dataset_provenance(fx.summary_for(tmp_path, "fixture-baseline"))

    def test_the_recorded_counts_are_shown(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "60" in cells(data.dataset_table)
        assert "3" in cells(data.dataset_table)

    def test_the_dataset_fingerprint_is_shown(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "f" * 64 in cells(data.dataset_table)

    def test_an_unrecorded_count_is_unavailable_not_derived(
        self, tmp_path: Path
    ) -> None:
        directory = fx.make_baseline_run(tmp_path)
        document = fx.dataset_document()
        del document["subject_count"]
        fx.write_json(directory / "dataset.json", document)
        data = load_dataset_provenance(fx.summary_for(tmp_path, "fixture-baseline"))
        rows = dict(data.dataset_table.rows)
        assert rows["Subject count"] == UNAVAILABLE_TEXT

    def test_the_split_audit_result_is_shown(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.split_audit_passed is True
        assert "audit" in cells(data.split_table)

    def test_the_fold_table_lists_every_fold(self, data) -> None:  # type: ignore[no-untyped-def]
        assert len(data.fold_table.rows) == 2

    def test_the_data_source_counts_are_reported(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.data_source_counts == (("synthetic", 60),)

    def test_the_targets_are_labelled_as_generated(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "generated by this repository" in (data.target_table.caption or "")

    def test_no_participant_label_is_claimed(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.target_table.caption or "").lower()
        assert "no validated participant label" in caption

    def test_an_adaptation_run_has_no_dataset_page(self, tmp_path: Path) -> None:
        fx.make_adaptation_run(tmp_path)
        data = load_dataset_provenance(fx.summary_for(tmp_path, "fixture-adaptation"))
        assert data.unavailable_reason is not None
        assert "no dataset provenance" in data.unavailable_reason

    def test_an_unreadable_dataset_degrades_with_a_reason(self, tmp_path: Path) -> None:
        directory = fx.make_baseline_run(tmp_path)
        fx.corrupt(directory / "dataset.json")
        data = load_dataset_provenance(fx.summary_for(tmp_path, "fixture-baseline"))
        assert data.unavailable_reason is not None
        assert "dataset.json" in data.unavailable_reason
        assert data.dataset_table is None


class TestSignalQuality:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_baseline_run(tmp_path)
        return load_signal_quality(fx.summary_for(tmp_path, "fixture-baseline"))

    def test_quality_is_never_called_engagement(self, data) -> None:  # type: ignore[no-untyped-def]
        text = row_text(data.missing_feature_table)
        for banned in ("disengaged", "inattentive", "poor participant", "engagement"):
            assert banned not in text

    def test_disengaged_appears_only_inside_its_own_denial(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.missing_feature_table.caption or "").lower()
        assert "not a person who was disengaged" in caption
        assert caption.count("disengaged") == 1

    def test_the_page_states_what_quality_is_not(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.missing_feature_table.caption or "").lower()
        assert "not engagement" in caption
        assert "not cognitive load" in caption
        assert "not model confidence" in caption

    def test_quality_is_never_called_confidence(self, data) -> None:  # type: ignore[no-untyped-def]
        # 'confidence' appears only inside the sentence denying the equation.
        text = cells(data.missing_feature_table)
        assert text.count("confidence") == text.count("not model confidence")

    def test_missingness_is_shown_as_a_percentage(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "10.00%" in cells(data.missing_feature_table)

    def test_the_overall_percentage_is_a_percentage(self, data) -> None:  # type: ignore[no-untyped-def]
        from engagevr.dashboard.formatting import format_value

        assert format_value(data.overall_missing_percentage) == "5.00%"

    def test_modality_coverage_is_listed(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "behavioural" in cells(data.modality_availability_table)
        assert "task" in cells(data.modality_availability_table)

    def test_absent_quality_is_unavailable_not_fabricated(self, tmp_path: Path) -> None:
        directory = fx.make_baseline_run(tmp_path)
        document = fx.dataset_document()
        document["missingness"] = []
        fx.write_json(directory / "dataset.json", document)
        data = load_signal_quality(fx.summary_for(tmp_path, "fixture-baseline"))
        assert data.unavailable_reason is not None
        assert "not been reconstructed" in data.unavailable_reason

    def test_an_adaptation_run_records_no_measurement_quality(
        self, tmp_path: Path
    ) -> None:
        fx.make_adaptation_run(tmp_path)
        data = load_signal_quality(fx.summary_for(tmp_path, "fixture-adaptation"))
        assert data.unavailable_reason is not None


class TestClassificationView:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_baseline_run(tmp_path)
        return load_classification(fx.summary_for(tmp_path, "fixture-baseline"))

    def test_the_class_labels_are_recovered(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.class_labels == fx.CLASSES

    def test_the_aggregate_table_shows_the_recorded_metrics(self, data) -> None:  # type: ignore[no-untyped-def]
        text = cells(data.aggregate_table)
        assert "0.6000" in text
        assert "macro_f1" in text

    def test_an_uncomputable_metric_is_unavailable_not_zero(self, data) -> None:  # type: ignore[no-untyped-def]
        row = next(
            r for r in data.aggregate_table.rows if r[0] == "logistic_regression"
        )
        column = data.aggregate_table.columns.index("balanced_accuracy")
        assert row[column] == UNAVAILABLE_TEXT

    def test_no_champion_wording_appears(self, data) -> None:  # type: ignore[no-untyped-def]
        text = row_text(data.aggregate_table)
        for banned in ("champion", "winner", "winning", "best model", "recommended"):
            assert banned not in text

    def test_sorting_is_described_as_descriptive(self, tmp_path: Path) -> None:
        fx.make_baseline_run(tmp_path)
        data = load_classification(
            fx.summary_for(tmp_path, "fixture-baseline"), sort_by="macro_f1"
        )
        caption = (data.aggregate_table.caption or "").lower()
        assert "sorted by macro_f1" in caption
        assert "descriptive sorting only" in caption

    def test_a_confusion_matrix_is_built_from_recorded_counts(self, data) -> None:  # type: ignore[no-untyped-def]
        assert len(data.confusion_matrices) == 1
        assert data.confusion_matrices[0].total == 40

    def test_a_synthetic_matrix_does_not_say_ground_truth(self, data) -> None:  # type: ignore[no-untyped-def]
        matrix = data.confusion_matrices[0]
        assert matrix.row_axis_label == SYNTHETIC_ROW_AXIS
        assert "ground truth" not in matrix.row_axis_label.lower()
        assert "truth" not in matrix.row_axis_label.lower()

    def test_the_row_axis_wording_follows_provenance(self) -> None:
        assert "synthetic" in row_axis_label(True)
        assert "synthetic" not in row_axis_label(False)

    def test_the_column_axis_names_the_prediction(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.confusion_matrices[0].column_axis_label == "predicted class"

    def test_calibration_is_reported_separately_from_accuracy(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "brier_score" in cells(data.calibration_table)
        assert "brier" not in " ".join(data.aggregate_table.columns).lower()

    def test_calibration_is_not_called_certainty(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.calibration_table.caption or "").lower()
        assert "is not certainty" in caption
        assert "is not signal quality" in caption

    def test_the_reliability_diagram_is_built_from_stored_bins(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.reliability_chart is not None
        assert data.reliability_chart.available
        assert "no calibration model is fitted" in (
            data.reliability_chart.x_axis_note or ""
        )

    def test_a_regression_run_gets_no_classification_view(self, tmp_path: Path) -> None:
        fx.make_baseline_run(tmp_path, task_type="regression")
        data = load_classification(fx.summary_for(tmp_path, "fixture-baseline"))
        assert data.unavailable_reason is not None
        assert "no classes" in data.unavailable_reason


class TestRegressionView:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_baseline_run(tmp_path, task_type="regression")
        return load_regression(fx.summary_for(tmp_path, "fixture-baseline"))

    def test_the_observed_axis_says_synthetic(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.observed_axis_label == "synthetic target"
        assert "true engagement" not in data.observed_versus_predicted.x_axis_label

    def test_the_scatter_uses_stored_values(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.observed_versus_predicted.available
        series = data.observed_versus_predicted.series[0]
        assert len(series.x_values) == 11  # one row has no predicted value

    def test_rows_with_no_prediction_are_excluded_and_counted(self, data) -> None:  # type: ignore[no-untyped-def]
        note = data.observed_versus_predicted.x_axis_note or ""
        assert "1 row(s)" in note
        assert "plotted as zero" in note

    def test_residuals_are_differences_of_stored_values(self, data) -> None:  # type: ignore[no-untyped-def]
        note = data.residual_versus_predicted.x_axis_note or ""
        assert "already recorded" in note
        assert "no model is re-run" in note.lower()

    def test_no_statistical_significance_is_implied(self, data) -> None:  # type: ignore[no-untyped-def]
        note = data.residual_versus_predicted.x_axis_note or ""
        assert "no statistical test is implied" in note.lower()

    def test_an_uncomputable_metric_is_unavailable(self, data) -> None:  # type: ignore[no-untyped-def]
        column = data.aggregate_table.columns.index("r_squared")
        assert data.aggregate_table.rows[0][column] == UNAVAILABLE_TEXT

    def test_missing_predictions_degrade_the_charts_with_a_reason(
        self, tmp_path: Path
    ) -> None:
        fx.make_baseline_run(tmp_path, task_type="regression", with_predictions=False)
        data = load_regression(fx.summary_for(tmp_path, "fixture-baseline"))
        assert not data.observed_versus_predicted.available
        assert "predictions.parquet" in str(
            data.observed_versus_predicted.unavailable_reason
        )
        assert data.aggregate_table is not None

    def test_a_classification_run_gets_no_regression_view(self, tmp_path: Path) -> None:
        fx.make_baseline_run(tmp_path)
        data = load_regression(fx.summary_for(tmp_path, "fixture-baseline"))
        assert data.unavailable_reason is not None


class TestFusionView:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_fusion_run(tmp_path)
        return load_fusion(fx.summary_for(tmp_path, "fixture-fusion"))

    def test_disagreement_has_its_own_table(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.expert_disagreement_table is not None
        assert "disagreement" in data.expert_disagreement_table.title.lower()

    def test_disagreement_is_not_called_calibrated_uncertainty(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.expert_disagreement_table.caption or "").lower()
        assert "not calibrated uncertainty" in caption
        assert (
            "calibrated uncertainty" not in data.expert_disagreement_table.title.lower()
        )

    def test_fusion_weights_are_called_support_weights(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "support weight" in data.fusion_support_weight_table.title.lower()

    def test_a_support_weight_is_not_a_probability_of_correctness(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.fusion_support_weight_table.caption or "").lower()
        assert "not a probability of correctness" in caption
        assert "not model confidence" in caption

    def test_the_weights_are_the_recorded_ones(self, data) -> None:  # type: ignore[no-untyped-def]
        text = cells(data.fusion_support_weight_table)
        assert "0.5500" in text
        assert "0.4500" in text

    def test_modality_availability_is_separate_from_quality(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.modality_availability_table is not None
        assert (
            data.modality_availability_table.title
            != data.fusion_support_weight_table.title
        )

    def test_a_missing_modality_is_not_missing_engagement(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.modality_availability_table.caption or "").lower()
        assert "not the absence of" in caption

    def test_an_untrained_expert_records_why(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "no usable window" in cells(data.expert_table)

    def test_a_robustness_scenario_that_failed_is_unavailable_not_zero(
        self, data
    ) -> None:  # type: ignore[no-untyped-def]
        row = next(r for r in data.robustness_table.rows if r[0] == "only_task")
        column = data.robustness_table.columns.index("accuracy")
        assert row[column] == UNAVAILABLE_TEXT

    def test_the_robustness_chart_keeps_the_gap(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.robustness_chart.available
        assert None in data.robustness_chart.series[0].y_values

    def test_no_champion_wording_in_the_strategy_table(self, data) -> None:  # type: ignore[no-untyped-def]
        text = row_text(data.strategy_table)
        for banned in ("champion", "winner", "best strategy", "recommended"):
            assert banned not in text

    def test_the_strategy_caption_denies_the_champion_reading(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.strategy_table.caption or "").lower()
        assert "is a champion" in caption
        assert "no model, fusion strategy, threshold, or policy" in caption


class TestPersonalizationView:
    @pytest.fixture
    def data(self, tmp_path: Path):  # type: ignore[no-untyped-def]
        fx.make_personalization_run(tmp_path)
        return load_personalization(fx.summary_for(tmp_path, "fixture-personalization"))

    def test_both_arms_are_reported_side_by_side(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.paired_metric_table.columns == (
            "metric",
            "population",
            "personalized",
        )

    def test_the_evaluation_window_counts_match(self, data) -> None:  # type: ignore[no-untyped-def]
        assert (
            data.population_evaluation_window_count
            == data.personalized_evaluation_window_count
            == 40
        )

    def test_a_negative_difference_is_retained(self, data) -> None:  # type: ignore[no-untyped-def]
        rows = dict(data.metric_delta_table.rows)
        assert rows["accuracy"].startswith("-")

    def test_the_difference_is_never_called_an_improvement(self, data) -> None:  # type: ignore[no-untyped-def]
        text = row_text(data.metric_delta_table)
        for banned in ("improve", "benefit", "gain", "better personalization"):
            assert banned not in text

    def test_the_synthetic_delta_is_labelled_as_synthetic(self, data) -> None:  # type: ignore[no-untyped-def]
        assert "synthetic software-check" in data.metric_delta_table.title

    def test_the_column_heading_says_difference(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.metric_delta_table.columns[1] == "personalized - population"

    def test_the_caption_denies_the_benefit_reading(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.metric_delta_table.caption or "").lower()
        assert "not a benefit" in caption
        assert "not an improvement" in caption

    def test_cold_start_counts_are_shown(self, data) -> None:  # type: ignore[no-untyped-def]
        assert data.cold_start_subject_count == 1
        assert "cold-start" in cells(data.coverage_table)

    def test_falling_back_is_described_as_designed_behaviour(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.coverage_table.caption or "").lower()
        assert "not a failure" in caption

    def test_the_subject_table_is_a_diagnostic_not_a_ranking(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.subject_diagnostic_table.caption or "").lower()
        assert "does not rank" in caption
        assert "pseudonymous" in caption

    def test_no_worst_or_best_subject_table_exists(self, data) -> None:  # type: ignore[no-untyped-def]
        text = row_text(data.subject_diagnostic_table)
        for banned in ("worst", "best", "rank", "top ", "leaderboard"):
            assert banned not in text

    def test_rank_appears_only_inside_its_own_denial(self, data) -> None:  # type: ignore[no-untyped-def]
        caption = (data.subject_diagnostic_table.caption or "").lower()
        assert "does not rank subjects" in caption
        assert caption.count("rank") == 1
