"""The typed message envelope shared by every protocol participant.

One envelope wraps exactly one payload.  The envelope carries identity,
ordering, timing, and provenance; the payload carries the message body.

Clock model
-----------
Three timestamps may appear on a message and they mean different things:

``sent_at_utc``
    The **sender's** wall-clock reading.  On a different machine this is
    a different clock; it is recorded, not trusted.

``sent_at_monotonic_seconds``
    The **sender's own** monotonic clock.  Its origin is arbitrary and
    is meaningful only for differences within that one sender.  It is
    never compared against the server's monotonic clock, because the two
    have unrelated origins.

``ingestion.server_received_at_utc`` (added by the backend, see
:mod:`engagevr.storage.manifest`)
    The receiver's wall-clock reading at ingestion.

No field in this module asserts that any two machines' clocks are
synchronized.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Self

from pydantic import BaseModel, Field, model_validator

from engagevr.protocol.messages import MessageSource, MessageType
from engagevr.protocol.version import PROTOCOL_VERSION
from engagevr.schemas.session import DataSource
from engagevr.utils.timestamps import monotonic_seconds, require_utc, utc_now

#: Permanent marker on any message whose content was generated by
#: software rather than observed.  Shares the wording used by the rPPG
#: layer so a single grep finds every synthetic artefact.
SYNTHETIC_LABEL = "SYNTHETIC"

#: Permanent marker added to a message as it is emitted by the replay
#: player.  A replayed synthetic message carries **both** labels.
REPLAY_LABEL = "REPLAY"


def new_message_id() -> str:
    """Return a fresh random message identifier."""
    return uuid.uuid4().hex


class MessageProvenance(BaseModel):
    """Where a message's content came from.

    ``synthetic_label`` is set to ``"SYNTHETIC"`` for every simulated
    message and is never cleared downstream.  A consumer that wants to
    exclude simulated data can do so on this field alone.
    """

    model_config = {"extra": "forbid"}

    data_source: DataSource = DataSource.SYNTHETIC
    synthetic_label: str | None = Field(
        default=SYNTHETIC_LABEL,
        description="Permanently 'SYNTHETIC' for generated content; else null.",
    )
    producer: str = Field(
        default="",
        max_length=256,
        description="Module or program that produced the content.",
    )

    @model_validator(mode="after")
    def _check(self) -> Self:
        is_synthetic = self.data_source is DataSource.SYNTHETIC
        if is_synthetic and self.synthetic_label != SYNTHETIC_LABEL:
            raise ValueError(
                f"a synthetic message must carry synthetic_label={SYNTHETIC_LABEL!r}"
            )
        if not is_synthetic and self.synthetic_label is not None:
            raise ValueError(
                "synthetic_label must be null for non-synthetic data "
                f"(data_source={self.data_source.value!r})"
            )
        return self


class ReplayMetadata(BaseModel):
    """Metadata added when a recorded message is replayed.

    This is **additive**.  The replayed envelope keeps its original
    ``source``, ``sequence_number``, timestamps, and provenance; the
    presence of this block is what marks it as a replay.  A replayed
    message is therefore never presentable as a live message, and a
    replayed synthetic message carries both ``SYNTHETIC`` (in
    provenance) and ``REPLAY`` (here).
    """

    model_config = {"extra": "forbid"}

    replay_label: str = Field(
        default=REPLAY_LABEL,
        description="Permanently 'REPLAY'.",
    )
    source_session_id: str = Field(
        description="Session the message was originally recorded under."
    )
    replay_session_id: str = Field(
        description="Session identifier this replay is publishing under."
    )
    replay_index: int = Field(ge=0, description="Position in the replay stream.")
    replay_speed: float = Field(
        ge=0.0, description="Speed multiplier; 0 means immediate."
    )
    replayed_at_utc: datetime
    original_arrival_index: int | None = Field(
        default=None,
        ge=0,
        description="Arrival order in the original recording, when known.",
    )

    @model_validator(mode="after")
    def _check(self) -> Self:
        if self.replay_label != REPLAY_LABEL:
            raise ValueError(f"replay_label must be {REPLAY_LABEL!r}")
        require_utc(self.replayed_at_utc, "replayed_at_utc")
        return self


class MessageEnvelope(BaseModel):
    """A single protocol message.

    ``payload`` is held as a plain JSON object here.  It is validated
    against the model registered for ``message_type`` by
    :func:`engagevr.protocol.validation.decode_message`, which is the
    only supported way to construct a trusted, typed message.  Keeping
    the envelope payload-agnostic lets the envelope be parsed (and its
    ``message_type`` reported in an error) even when the payload itself
    is malformed.
    """

    model_config = {"extra": "forbid"}

    protocol_version: str = Field(default=PROTOCOL_VERSION)
    message_id: str = Field(
        default_factory=new_message_id, min_length=1, max_length=128
    )
    message_type: MessageType
    session_id: str = Field(min_length=1, max_length=128)
    source: MessageSource
    sequence_number: int = Field(
        ge=0,
        description=(
            "Per-source counter within a session. Must not decrease and "
            "must not repeat."
        ),
    )
    sent_at_utc: datetime = Field(
        description="Sender's wall-clock reading, timezone-aware."
    )
    sent_at_monotonic_seconds: float = Field(
        description=(
            "Sender's own monotonic clock. Arbitrary origin; comparable "
            "only against other readings from the same sender."
        )
    )
    payload: dict[str, object] = Field(default_factory=dict)
    correlation_id: str | None = Field(
        default=None,
        max_length=128,
        description="message_id of the message this one responds to.",
    )
    provenance: MessageProvenance = Field(default_factory=MessageProvenance)
    replay: ReplayMetadata | None = Field(
        default=None,
        description="Present only on replayed messages. Never on live ones.",
    )

    @model_validator(mode="after")
    def _check(self) -> Self:
        require_utc(self.sent_at_utc, "sent_at_utc")
        return self

    def to_json_dict(self) -> dict[str, object]:
        """Serialize to a JSON-compatible dict, ready for ``json.dumps``."""
        return self.model_dump(mode="json")

    def with_replay_metadata(self, metadata: ReplayMetadata) -> MessageEnvelope:
        """Return a copy carrying ``metadata``, leaving this instance intact.

        Nothing else is rewritten: source, sequence number, timestamps,
        and provenance are preserved exactly as recorded.
        """
        return self.model_copy(update={"replay": metadata}, deep=True)


def build_envelope(
    *,
    message_type: MessageType,
    session_id: str,
    source: MessageSource,
    sequence_number: int,
    payload: BaseModel | dict[str, object],
    provenance: MessageProvenance | None = None,
    correlation_id: str | None = None,
    sent_at_utc: datetime | None = None,
    sent_at_monotonic_seconds: float | None = None,
    message_id: str | None = None,
) -> MessageEnvelope:
    """Construct an envelope around an already-typed payload.

    Passing a Pydantic payload model is the normal path; the model is
    dumped in JSON mode so the envelope only ever holds JSON values.
    """
    body = (
        payload.model_dump(mode="json") if isinstance(payload, BaseModel) else payload
    )
    return MessageEnvelope(
        message_type=message_type,
        message_id=message_id if message_id is not None else new_message_id(),
        session_id=session_id,
        source=source,
        sequence_number=sequence_number,
        sent_at_utc=sent_at_utc if sent_at_utc is not None else utc_now(),
        sent_at_monotonic_seconds=(
            sent_at_monotonic_seconds
            if sent_at_monotonic_seconds is not None
            else monotonic_seconds()
        ),
        payload=body,
        correlation_id=correlation_id,
        provenance=provenance if provenance is not None else MessageProvenance(),
    )
